readme.md
This commit adds a new awesome list for awesome niche job boards.  New
boards are popping up by the day, so it would be helpful to have a
curated list of these awesome job boards for people to reference.
=> Add Niche Job Boards

readme.md
I changed my Github's username (links still work : *Web links to your existing repositories will continue to work* from [Github doc](https://help.github.com/articles/what-happens-when-i-change-my-username/)) but I prefer to edit them here.
=> change GIF & OpenSourcePhotoGraphy link

contributing.md
I updated the title-case link to go to http://titlecapitalization.com. Contributors only need to enter the title and it will automatically be title-cased. I use this resource in some of my repos' for contributors and think it will be much more simpler than the previous resource.
=> Changed link for title-casing resource

contributing.md
By browsing through the PRs that we're getting on a daily basis, it seems like it would be easier to request from the people to submit a link directly in the body of the commit message. That way, we can just click on it instead of switching to the `Files` tab, copying it and then pasting it in a new browser tab.
It's just something that came to my mind like right now, so I'm gonna wait for the feedback.
=> Adds one line to the "Adding to this list" section

readme.md
https://github.com/mhinz/vim-galore
Why?
[vimawesome.com](http://vimawesome.com) isn't like any of the other awesome lists here. It's just a list of 14072 plugins which nobody would have the time to read through. Vim Galore has a guide, many tips as well as a *selection* of plugins and colour schemes.
=> Replace 'Vim Awesome' with 'Vim Galore'

readme.md
When I came to the README on github recently, I encountered this:
It looks like rawgit has made some changes and they've added a production url. The url that was in use was for their dev/test environment that includes the following restrictions:
> * For sharing low-traffic, temporary examples or demos with small numbers of people.
> * Excessive traffic may lead to throttling and blacklisting.
=> update logo in README to use production rawgit url

contributing.md
I changed the case of “Awesome” in this link to match other links’
formatting and the case of the section it links to for consistency.
=> Minor edit

readme.md
I’ve moved “FOSS for Developers” under Dev Environment and “Open Source Documents” under Media
(https://github.com/sindresorhus/awesome/pull/557#issuecomment-192227638) as part of Issue #550, cleaning up the Misc. category.
=> Moved resources under appropriate cateorgies

readme.md
Add the Serverless Framework (http://serverless.com) to the list of back-end web technologies.
=> Add Serverless Framework

readme.md
Hello,
Some urls were forwarding (301) to a repo with other name, due to account or repo name changes.
Example:
https://github.com/yenchenlin1994/awesome-watchos
forwards to 
https://github.com/iCHAIT/awesome-macOS
Now, instead of 301, everyone will get a 200. Not the best pull request ever, but I was using your list and I noticed these differences. (also, good job with the awesome lists! :+1: )
=> Change forwarding urls - no more 301

readme.md
Looking at the other sections (Books, Databases, etc), this would be better pluralized too.
=> Pluralize title of CMS section

readme.md
Hyperterm's name is changing to Hyper today - as such, the Awesome repo's name has changed. The commit changes the linking text and the URL to the new one.
I was actually just about to ask you what I should do to resolve what I thought was going to be all the broken backlinks to the old repo - but I just tired it, and the old URL redirected! WOW!
Thanks!
=> Update Awesome Hyperterm to Awesome Hyper

readme.md
**https://github.com/thibmaek/awesome-raspberrypi**
**This list is a collection of tools, projects, images and resources around Raspberry Pi**
This list is a collection of tools, projects, images and resources around Raspberry Pi
=> Add Raspberry Pi

readme.md
**https://github.com/derimagia/awesome-alfred-workflows**
**Workflows for Alfred on macOS.**
=> Add Alfred Workflows

readme.md
https://github.com/drmonkeyninja/awesome-textpattern
This is the awesome list for the [Textpattern CMS](http://textpattern.com) and has been around for well over a year now. The list uses Textile instead of Markdown, but this is because Textile is the default markup syntax used by the Textpattern community and so was chosen to encourage participation.
=> Add Textpattern

readme.md
**https://github.com/arbox/nlp-with-ruby**
**This list encompasses Ruby related projects for processing natural language texts. It it an attempt to create a curated list with only working software and no dead links. The list is focused only on Ruby so it does not duplicate available lists.**
- This pull request has a descriptive title. For example, `Add Name of List`, not `Update readme.md` or `Add …
=> Add NLP with Ruby

readme.md
**https://github.com/timofurrer/awesome-asyncio**
**A curated list of awesome Python asyncio frameworks, libraries, software and resources.**
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be …
=> Add Python Asyncio

readme.md
[Awesome JavaScript learning resources ](https://github.com/micromata/awesome-javascript-learning-resources)
This list is about JavaScript – the language. Not about APIs, tooling, frameworks or other aspects of todays JavaScript ecosystem.
Therefore the list is small and focused to the best resources. Reason: We don’t want to frustrate people who like to learn JavaScript with a list that:
- is too long to get through it
- offers too many possibilities
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a …
=> Add JavaScript Learning

create-list.md
I wrote [this Yeoman generator](https://github.com/dar5hak/generator-awesome-list) to make it easy to get started building an awesome list, and thought maybe the readers of this doc might find it useful. The generated directory structure looks [like this](https://github.com/dar5hak/generator-awesome-list/tree/master/app/templates).
Is it okay to add it here?
- This pull request has a descriptive …
=> Add a link to Yeoman generator for awesome lists

readme.md
I believe that RichardLitt/endangered-languages _is_ an awesome list. However, it does not match
the stipulations set in https://github.com/sindresorhus/awesome/issues/926 as to what an awesome
list should look like. For instance, I use GitHub descriptions instead of other descriptions for
repositories. I also include everything I can, because that is the point of the list - we use
stars to show what is popular, which is a metric of awesome contents, as opposed to having only
awesome contents. I do not want to change the whole list to match the awesome-styleguides, as that
would be arduous and I am not convinced it would improve the point of the list.
I have written about this list elsewhere, and I would like to keep it as it is currently formatted,
although I agree that it would be great …
=> Remove Endangered Languages list

readme.md
https://github.com/RyanZim/awesome-npm-scripts
I couldn't find an awesome list relating to npm scripts and using npm as a build tool, so I wrote one. This is a resubmission of https://github.com/sindresorhus/awesome/pull/775; the list has been expanded since then.
- Include a short …
=> Add npm scripts

readme.md
**[awesome-python-scientific-audio](https://github.com/faroit/awesome-python-scientific-audio/)**
**The aim of this repository is to create a comprehensive, curated list of python software/tools related and used for scientific research in audio/music applications.**
-  [X] It's the result of hard work and the best I could possibly produce.
-  [ ] The image should link to the project website or any relevant website.
=> Add Python Scientific Audio

readme.md
**[https://github.com/analyticalmonk/awesome-neuroscience]**
**[This is a curated list of awesome neuroscience libraries, software and any content related to the domain. The popularity of machine learning, neural networks and related technologies has led to an increased interest in study of the human brain. Neuroscience is a fascinating subject and this list will help enthusiasts and practitioners to explore its computational aspects.]**
- This pull …
=> Add Neuroscience

readme.md
Previous PR: https://github.com/sindresorhus/awesome/pull/988
**https://github.com/unicodeveloper/awesome-nextjs**
**Curated list of resources: books, videos, articles about using Next.js.**
- Include a short description about the list project/theme. It should not describe the list …
=> Add Next.js

readme.md
**https://github.com/hgupta9/awesome-actionscript3/**
**Awesome tools, libraries and components for ActionScript 3 and Adobe AIR.** 
I have complied with the below requirements:
1. Created 30+ days ago (Jun 10th). 60 commits. Hand curated.
2. Result of hard work and truly the best I could make it. 
3. Only has awesome items.
4. Not a duplicate.
5. Has a TOC. Well categorized. Has a logo of Flash & AIR on top-right.
6. All entries have a hand-written description, not just a copy-paste from the project.
7. All entries are FOSS unless specified in the section heading (only a few tools are Commercial)
8. Has consistent formatting 
9. No travis badge in the readme
=> Add ActionScript 3

readme.md
https://github.com/chasegiunta/awesome-craft
Curated list of awesome Craft CMS plugins, technical articles/tutorials, and praise articles (sought by many developers promote & compare the platform). Craft is a CMS that’s laser-focused on doing one thing really, really well: _managing content_. Built to be as flexible as possible, without compromising on the ease of use for content authors.
- This pull request has a descriptive title.<br>For example, …
=> Add Craft CMS

readme.md
**https://github.com/johnjago/awesome-uncopyright**
**This is a list of art, books, images, and other works that are in the public domain. It also contains resources such as books, articles, and talks that discuss the public domain. The goal of this list is to make it easy to find a variety of works that are free of copyright restrictions, which can be useful when creating presentations, etc.**
- This pull request has a descriptive title.<br>For …
=> Add Uncopyright

readme.md
Renamed list "Continuous Delivery" into "Continuous Integration and Continuous Delivery" as the list is about both, and there is no mention of integration anywhere else in the readme.
=> Rename list Continuous Delivery

readme.md
shortens:
`https://github.com/fukuball/Awesome-Laravel-Education/blob/master/langs/en_US.md`
to:
`https://github.com/fukuball/Awesome-Laravel-Education`
for consistency
Cannot shorten `https://github.com/shlomi-noach/awesome-mysql/blob/gh-pages/index.md`, made shlomi-noach/awesome-mysql#63
=> Shorten the Laravel Education link

contributing.md
Old (dead): http://titlecapitalization.com
New (up): http://titlecase.com
=> Update title casing website in contributing.md

readme.md
Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category. The Adafruit CircuitPython awesome list is at https://github.com/adafruit/awesome-circuitpython
[https://github.com/adafruit/awesome-circuitpython]
[Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category.]
We have read the guidelines multiple times and have tried to ensure every single item is covered.
**[https://github.com/adafruit/awesome-circuitpython]**
**[Request to add the Adafruit Industries curated awesome list devoted to CircuitPython, a microcontroller based version of Python, to the Python category.]**
**Please read it multiple …
=> Add CircuitPython

readme.md
The fuse-awesome repo has moved to the fuse-compound organization instead of being a private repo of vinkla. So here's an updated link.
=> Update outdated link

readme.md
**https://github.com/web-padawan/awesome-lit-html#readme**
**A curated list of awesome lit-html resources. lit-html — an efficient, expressive, extensible HTML templating library for JavaScript.**
- Include a short description about the project/theme of the list. **It should not …
=> Add lit-html

readme.md
This PR adds https://github.com/uraimo/awesome-software-patreons , a list of patreon accounts of individual software developers or software projects.
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - …
=> Add Software Patreons

readme.md
I added *'Asyncronous non-blocking event-driven'* in front of the original description. I think they are core characteristics of Node.js, so this will more precisely depict what actually Node.js is, without loosing brevity. Also, these words are used on the first line of [introduction on official Node.js website](https://nodejs.org/en/about/). What's more, by this update, someone who searches something like "async non-blocking framework" might find this repository.
By the way, I reviewed #1431 and #628. 
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also …
=> Improve Node.js description

readme.md
1. Whether an app is native matters. Flutter is to build **native** app, so I added the word "**native**".
2. Whether to write code once, or twice is a significant factor as well. So I explicitly mentioned "**single codebase**".
3. Which language to use counts much. Hence I let people see "**Dart**".
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to …
=> Improve Flutter description

readme.md
Just a URL update to the Umbraco Awesome list, as it has moved away from an individual and under an Umbraco community organization GitHub account.
=> Update Umbraco list URL

readme.md
MySQL link points to wrong page.
Update:
https://github.com/shlomi-noach/awesome-mysql/blob/gh-pages/index.md
To:
https://github.com/shlomi-noach/awesome-mysql#readme
=> Fix MySQL list URL

readme.md
**[https://github.com/ecohealthalliance/awesome-parasite/](https://github.com/ecohealthalliance/awesome-parasite/)**
**A curated list of awesome information and open-access databases related to parasites and host-pathogen interactions.**
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly …
=> Add Parasite

readme.md
**https://github.com/Tom2718/Awesome-Ethereum**
Ethereum is a decentralized platform for creating smart contracts. There are lots of resources available that are outdated and deprecated. This awesome list aims to keep only up-to-date and relevant links. Furthermore, other lists focus too much on bringing publicity to other projects. I don't want this to happen and so won't include any projects being built on top of Ethereum. 
**Reviewed PRs**
[1431 Comment](https://github.com/sindresorhus/awesome/pull/1431#issuecomment-434213289)
[1437 Comment](https://github.com/sindresorhus/awesome/pull/1437#issuecomment-434211965) …
=> Add Ethereum

readme.md
https://github.com/MFatihMAR/Awesome-Game-Networking
Game networking is a subset of computer networking that covers data replication, state synchronization, snapshot interpolation, client prediction, lag compensation, bandwidth optimization and many more techniques involved in multiplayer online gameplay programming.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. …
=> Add Game Networking

readme.md
Add https://github.com/liuchong/awesome-roadmap
I've just made a collection of roadmaps, will add more in the following days.
Also I've found an issue https://github.com/sindresorhus/awesome/issues/1470 refer to this, so I'd like to share my list here.
=> Add Roadmaps

readme.md
**https://github.com/matchai/awesome-pinned-gists**
Pinned Gists are a recently added feature to GitHub, allowing you to pin Gists to your GitHub profile, previewing either the first few lines of text in the Gist, or the image within it. This repo is meant to showcase tools used to dynamically update pinned Gists with content.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you …
=> Add Pinned Gists

readme.md
- I have read and understood the [instructions for creating a …
=> Delphi list was renamed to Pascal

readme.md
...and move under Business heading.
https://github.com/cjbarber/ToolsOfTheTrade
=> Update Tools of the Trade description

readme.md
https://github.com/irazasyed/awesome-cloudflare
> Curated list of [Cloudflare](https://www.cloudflare.com) worker recipes, open-source projects, guides, blogs, and other resources.
Unicorn 🦄
PRs Reviewed:
- https://github.com/sindresorhus/awesome/pull/1579#issuecomment-515718762
- https://github.com/sindresorhus/awesome/pull/1582#issuecomment-515718228
- https://github.com/sindresorhus/awesome/pull/1589#issuecomment-515718627
- https://github.com/sindresorhus/awesome/pull/1592#issuecomment-516107011
=> Add Cloudflare

readme.md
**https://github.com/rafaskb/awesome-libgdx#readme**
**LibGDX is a powerful game framework in Java, similar to the one used by Minecraft. This list is a curated collection of resources, add-ons, and guides to help LibGDX developers make awesome games.**
**PR Reviews:**
- https://github.com/sindresorhus/awesome/pull/1589#issuecomment-520162680
- https://github.com/sindresorhus/awesome/pull/1573#issuecomment-520164134
-----
Try to prioritize unreviewed PRs, but you can …
=> Add libGDX

readme.md
**https://github.com/dvergar/awesome-haxe-gamedev**
**This is a list of resources for game development in the haxe language.**
PR Review 1 : https://github.com/sindresorhus/awesome/pull/1563#issuecomment-496483878
PR Review 2 : https://github.com/sindresorhus/awesome/pull/1538#issuecomment-496475614
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the …
=> Add Haxe Game Development

readme.md
**https://github.com/caufieldjh/awesome-bioie#readme**
**How to extract information from unstructured biomedical data and text.**
Pull requests reviewed:
#1615 
#1609 
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be …
=> Add Biomedical Information Extraction

readme.md
**https://github.com/pajaydev/awesome-web-performance-budget**
**Curated list of why, how and tools to implement Web Performance Budget. Included few cases studies which will be helpful to others.**
PRs reviewed:
https://github.com/sindresorhus/awesome/pull/1612
https://github.com/sindresorhus/awesome/pull/1635
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to …
=> Add Web Performance Budget

readme.md
**https://github.com/GustavBertram/awesome-common-lisp-learning-list/#readme**
**This is a list of Common Lisp learning resources, and reviews of those resources.**
Reviewed PRs: #1666, #1677, #1653, #1644, #1679
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to …
=> Add Common Lisp Learning

readme.md
https://github.com/danvoyce/awesome-creative-tech-events/tree/master
It's quite hard to keep in the loop of all the more niche events / conferences / meetups out there, so hopefully this will help with the slightly niche subject of creating coding / tech.
I've also added a new `Events` category as I felt it didn't fit under any others, and there's starting to be a few other events lists that could also sit under this.
PR's reviewed: #1676  #1677 
Try to prioritize …
=> Add Creative Tech Events

readme.md
https://github.com/ltchris/awesome-contexture
This awesome list covers the best and the brightest of the Contexture ecosystem. Contexture is used for abstracting queries/filters and results/aggregrations from different backing data stores like ElasticSearch and MongoDB.
This list includes the best applications, libraries, documentation, and other resources from the Contexture ecosystem. It is a great way for the community to see the best of Contexture in one place and to be able to contribute to the growing ecosystem. 
Reviewed PRs:
https://github.com/sindresorhus/awesome/pull/1725#issuecomment-596160653
https://github.com/sindresorhus/awesome/pull/1722#issuecomment-596160909
https://github.com/sindresorhus/awesome/pull/1728#issuecomment-596244280 …
=> Add Contexture

readme.md
I noticed that there are quite a few resources related to (Software) Testing topic in the Miscellaneous section so this change should organize them a bit:
- separate Testing section created;
- testing-related lists moved from Miscellaneous section to Testing;
- description added for Selenium list.
=> Create Testing section

readme.md
https://github.com/nadunindunil/awesome-material-ui
Material-UI is a successful react component library and it is one of the famous(more than 50k stars) react libraries.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be …
=> Add Material-UI

readme.md
https://github.com/mgramin/awesome-db-tools
This is a community driven list of database tools (ide, cli, managing, monitoring, migrations, modellers, visualization etc)
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- You have read and understood the [instructions for …
=> Add Database Tools

readme.md
**https://github.com/MartinMiles/Awesome-Sitecore**
**A missing list for such a top-rated CMS  as Sitecore**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration.
- You have …
=> Add Sitecore

readme.md
https://github.com/Richienb/awesome-ponyfills
People can use these modules when looking to support older browsers or node versions without polluting the prototype.
https://github.com/sindresorhus/awesome/pull/1653
https://github.com/sindresorhus/awesome/pull/1660
cc @sindresorhus
=> Add Ponyfills

readme.md
https://github.com/mjhea0/awesome-fastapi
The list is about [FastAPI](https://fastapi.tiangolo.com/), a Python-based, async web application framework. It should be included since (1) the isn't already a FastAPI awesome list and (2) FastAPI is a popular framework for Python web app development.
=> Add FastAPI

readme.md
**https://github.com/kdeldycke/awesome-management**
**Why is this list awesome?**
You wonder what it looks like to be a manager from the inside? You just started your first job as the leader of a team? You're stuck into the day-to-day operations of the job? You need to move up to the next level? This awesome list is written for you!
This body of work stands out from generic leadership and management literature, by providing uncompromising insights and practical advices to bootstrap your journey into the management career track, from a technical background.
This list provides a progression to help with the transition to management. From general to specifics. It starts with an overview of the role, then describes its requirements, its position relatives to others. Then we delves into the …
=> Add Engineering Team Management

pull_request_template.md
Now that we want users to use the `main` branch instead of `master` branch, this PR updates the LICENCE setup link accordingly.
=> Update pull request template link to use `main` branch

readme.md
This PR makes no substantive changes to the list. Instead, it simply corrects links to two lists I maintain by updating the URL referencing their GitHub repository addresses, which future-proofs the links in the event their current redirects stop working.
=> Correct links to two Awesome lists whose username had changed

readme.md
**[Awesome Web Monetization repository](https://github.com/thomasbnt/awesome-web-monetization#readme)**
**[Web Monetization](https://webmonetization.org) is becoming more and more used on the Internet. It would be interesting for people to turn to a new payment method for websites such as blogs, videos, newsletters or shared photos whether it is monetized according to the time spent reading/watching. And all this natively on your computer.**
___
Checked PR's:
#1800
#1811 
#1795 
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is% …
=> Add Web Monetization

readme.md
**https://github.com/TheComputerM/awesome-svelte**
Svelte is a new and upcoming compiler that compiles to js and makes faster apps as there is no almost no runtime,
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. …
=> Add Svelte

readme.md
**https://github.com/mbiesiad/awesome-translations**
**This list contains libraries, platforms, apps and articles about translation and localization. This list should be included because languages are barriers for people, and such a list can help a little to bridge those barriers by helping developers localize their apps, introducing new translation technologies and new projects in this field.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to …
=> Add Translations

readme.md
https://github.com/chalice-dev/awesome-chalice#readme
Chalice is a framework for writing serverless Python applications on AWS Lambda.
I reviewed:
- https://github.com/sindresorhus/awesome/pull/1983
- https://github.com/sindresorhus/awesome/pull/1954
https://github.com/chalice-dev/awesome-chalice#readme
This is an awesome list of need-to-know links relating to AWS Chalice, a previously hidden gem for writing serverless Python applications on AWS Lambda.
Try to …
=> Add Chalice

.github/workflows/main.yml, .github/workflows/repo_linter.sh, readme.md
Note: This PR is a repeat of #1851 since the fork or original fork was deleted. This PR address comments there.
I really appreciate this project and wanted to try to give back so it's a little easier for everyone involved.
To that end, I created this PR to **automatically lint new lists** when someone opens a PR to add them.
- It will save time of maintainers by allowing them to look at the error message first
- It will provide immediate feedback to people who make a PR
- It helps people having trouble installing `awesome-lint`
- It is free
- As far as I know, there is no risk to users or maintainers.
- PR will lint **NEW** lists that are requesting to be added.
- PR will **NOT** lint [this](https://github.com/sindresorhus/awesome/) repo itself. If that functionality is desired it can …
=> Run `awesome-lint` on new additions

.github/workflows/repo_linter.sh
Addresses https://github.com/sindresorhus/awesome/pull/1962#issuecomment-830787984
The problem was that you need to add a `--` between the branch and the file path.
https://git-scm.com/docs/git-diff
Maybe I removed that part by accident when refactoring the code.
Anyway, this is working now.
Sorry for the hiccup @sindresorhus
=> Fix git diff command in repo linter

readme.md
Add APA Technology Divisions GitHub Repo for Urban Planning.
https://github.com/APA-Technology-Division/urban-and-regional-planning-resources
Working Previous Link is [here](https://github.com/APA-Technology-Division/planning-technology-resources).
This list is sponsored by the [APA Technology Division](https://tech.planning.org/) and is intended to catalog urban planning tools  and resources. 
We have an issue discussing compliance with awesome-list standards here. 
https://github.com/APA-Technology-Division/planning-technology-resources/issues/14
We have reviewed there requirements for inclusion, and have made edits sufficient to pass awesome-lint checks. We needed to add a disable flag for our TOC (there was error with no clear direction to resolve), but are willing to work through …
=> Add Urban & Regional Planning

readme.md
**https://www.trackawesomelist.com**
**This is another way to browse awesome repos, for example, https://www.trackawesomelist.com/sindresorhus/awesome/ , we can view it by time. It solved my needs, when I stared some awesome repos before, that's the thing. With this, I can get the latest updates of my favorite awesome repo. I wonder if you also need it. I think it's nice if this is listed at Related category**
I reviewed https://github.com/sindresorhus/awesome/pull/2010 , https://github.com/sindresorhus/awesome/pull/2035  …
=> Add Track Awesome List

readme.md
https://github.com/friedger/awesome-stacks-chain#readme
**This is a list of awesome resources and projects on the Stacks blockchain, maintained by the Stacks community. Stacks is a blockchain project that brings smart contracts to a chain that has native visibility into Bitcoin state. There are many current and in-progress projects against the Stacks chain, and as a community we feel passionate about being included in the Awesome list.**
PRs reviewed
- #2019 
- #2023 
---
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen) …
=> Add Stacks

readme.md
**https://github.com/dersvenhesse/awesome-scriptable#readme**
**The iOS app Scriptable allows users to create automations in JavaScript. With the release of widgets in iOS 14 and the power of Scriptable, users created wonderful widgets which are curated in this list.**
**You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to …
=> Add Scriptable

readme.md
As we've going through the process of rebranding organisation (GraknLabs becomes Vaticle and Grakn becomes TypeDB), it makes sense to update the reference in Awesome Lists
=> Update link to Grakn

readme.md
https://github.com/godotengine/awesome-godot
Updating Awesome Godot list link from the now unmaintained Calinou one to the godotengine maintained one
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at …
=> Update link to Godot list

readme.md
https://github.com/naimo84/awesome-nodered
Node-RED is a programming tool for wiring together hardware devices, APIs and online services.
It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click. 
This list is about useful third-party nodes and basics.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the …
=> Add Node-RED

readme.md
https://github.com/dhondta/awesome-executable-packing
This provides a full bibliography, links to packers, unpackers and other related tools for executable formats (PE, ELF, ...). This aims to complement the *Malware Analysis* list.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you …
=> Add Executable Packing

readme.md
Adds reference to Algorand themed awesome list. Maintained by community developers and solution architects from Algorand.
**[Awesome Algorand](https://github.com/aorumbayev/Awesome-Algorand)**
**An awesome list created for Algorand Blockchain development community. References and aggregates all known Algorand related resources useful for development or getting familiar with the ecosystem of tools. Actively maintained by community and several engineers from Algorand.**
>Uses awesome-list linter tool as part of the CI. Additionally hosted on gh-pages and available at [awesomealgo.com](https://awesomealgo.com).
- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be …
=> Add Algorand

readme.md
Repository does not exist anymore
Didn't follow template due to not adding.
Unicorn
=> Remove Social Media Share Links

readme.md
https://github.com/erwanlemerrer/awesome-audit-algorithms
A curated list of audit algorithms for getting insights from black-box algorithms.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which …
=> Add Audit Algorithms

readme.md
**https://github.com/kareniel/awesome-evm-security**
**This list covers the many domains that a security professional would want information on to get started when working in the EVM space.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or …
=> Add EVM Security

readme.md
[Awesome Open Hardware](https://github.com/delftopenhardware/awesome-open-hardware#readme)
The awesome Open Hardware list is made for people wanting to learn more about open source hardware (projects). On the one hand it has the most awesome example project for people to get inspired. On the other hand it has more in depth papers and background information about the topic.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through …
=> Add Open Hardware

readme.md
**https://github.com/brootware/awesome-cyber-security-university**
**Cyber Security University is A curated list of awesome and free educational resources that focuses on learn by doing.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull …
=> Add Cyber Security University

readme.md
Renames the section 'Higher Education' to 'Health and Social Sciences' as 'Higher Education' applies to many items in the list. At the same time we are reducing the number of items in the 'Miscellaneous' section.
=> Rename Higher Education

readme.md
**https://github.com/michelpereira/awesome-open-source-games**
The purpose of this is to keep a list of Open Source Games that are hosted on GitHub, so the others can fork and learn more about gaming.
- The list is around for 4+ years.
- It's maintainer is no longer maintaining it
- As suggested at #1198 I want to be the new maintainer
- Reviewed PRs: #2111 
- Comments made: #2099 (comment)
- Suggestion made to other lists: #1907 (comment)
Fixes #1198
Try to …
=> Add Open Source Games

readme.md
Adds:
```md
- [Hydrogen](https://github.com/shopify/awesome-hydrogen#readme) - Edge-first framework for building Shopify storefronts with React
```
https://github.com/shopify/awesome-hydrogen#readme
This list is to help users of the Hydrogen framework find relevant tools and resources to help them accelerate their build. It is a place for us to show off the best of the community and various integrations with the Hydrogen framework. …
=> Add Hydrogen

readme.md
**https://github.com/master-co/awesome-master-css#readme**
**Master CSS is a virtual CSS language with enhanced syntax, efficiently build your UI and design system with HTML only.**
Reviewed PRs:
- https://github.com/sindresorhus/awesome/pull/2327#issuecomment-1221734776
- https://github.com/sindresorhus/awesome/pull/2287#issuecomment-1221757581
- https://github.com/sindresorhus/awesome/pull/2169#issuecomment-1229830939
Try to prioritize unreviewed PRs, but you can …
=> Add Master CSS

readme.md
This PR adds [an awesome-list for Supabase](https://github.com/lyqht/awesome-supabase). It contains official + community starters & resources, including community-made tools/libraries, articles, videos, livestreams and courses.
- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
- ❌ `- [iOS](…) - Resources and tools for iOS development.`
- ❌ `- [Framer](…)`
- ❌ `- [Framer](…) - prototyping interactive UI designs`
- Example: `- [Software Architecture](https://github.com/simskij/awesome-software-architecture#readme) - The discipline of designing and …
=> Add Supabase

readme.md
This PR updates the link to the Web Components awesome list, which has been transferred and renamed:
- Before: https://github.com/mateusortiz/webcomponents-the-right-way
- After: https://github.com/web-padawan/awesome-web-components
Background: @mateusortiz has created this repo, but he no longer works on maintaining it.
We agreed on this with Mateus as he has been inactive on GitHub for more than 2 years.
Also note that I've been maintaining this list since December 2018 for more than 4 years - see [this post](https://dev.to/webpadawan/web-components-the-right-way-project-relaunch-20d7).
For more on the reason for renaming see this PR: https://github.com/web-padawan/awesome-web-components/pull/69
hanks in advance for taking a look at this PR 🙏  I'll try to do my best to review two PRs in …
=> Update link to Awesome Web Components

readme.md
**[https://github.com/n0kovo/awesome-password-cracking](https://github.com/n0kovo/awesome-password-cracking)**
**A list of tools, research, papers and other projects related to password cracking and password security.**
Reviewed PRs:
https://github.com/sindresorhus/awesome/pull/2383#issuecomment-1253947475
https://github.com/sindresorhus/awesome/pull/2382#issuecomment-1253953085
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go …
=> Add Password Cracking

readme.md
**https://github.com/tomodachi94/awesome-computercraft**
**ComputerCraft is a Minecraft mod which adds programmable computers to the game.**
Reviewed PRs:
- #2391
- #2274
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be …
=> Add ComputerCraft

readme.md
https://github.com/steven2358/awesome-generative-ai
A list of models and services that allow people to generate text, code, images, audio, and so on. The included resources are "modern", meaning most of them are based on neural networks known as Large Language Models that have started to appear in 2020 with GPT-3. While the first models focused on the generation of text, and then computer code, in 2022 these models have meade headlines with the release of models that generate high-quality imagery. The list is ordered by the type of content that is to be generated, i.e. text, code, image, video, audio, and more.
- **Don't waste my time.** Do a good job, adhere to all the guidelines, and …
=> Add Generative AI

readme.md
**https://github.com/zolagonano/awesome-zeronet#readme**
ZeroNet is a distributed web-like peer-to-peer network, this list is going to help new users to find the sites, tools, implementations, plugins, and guides on ZeroNet
Reviewed PRs:
- #2275 
- #2325 
New reviewed PRs:
- #2316 
- #2302 
- #2370 
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the …
=> Add ZeroNet

readme.md
https://github.com/dribdat/awesome-hackathon
Tips and tools for running tolerant and productive hackathons. We started this list a year ago to connect with other hackathon organizers. In my opinion, hackathons are placed perfectly at the intersection of awesome "Learning" and "Security" topics.
- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive. :heavy_check_mark: 
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** :heavy_check_mark: 
- [#2431](https://github.com/sindresorhus/awesome/pull/2431#pullrequestreview-1188329868)
- [#2428](https://github.com/sindresorhus/awesome/pull/2428#pullrequestreview-1188337238)
- You have read and understood the [instructions for creating …
=> Add Hackathon

readme.md
https://github.com/bytecauldron/awesome-gamemaker
GameMaker is a popular, beginner-friendly video game engine for 2D (and 3D) titles. The community has created many great extensions and resources over the years that are worth sharing with both beginner and advanced game developers. …
=> Add GameMaker

readme.md
Hello Unicorn,
I've created [Awesome Certificates](https://github.com/PanxProject/awesome-certificates#readme)!
**The project's aim is to provide free certifications & digital badges to earn, currently in computer science and infromation technology.**
I have reviewed and commented on these PRs: [#2453](https://github.com/sindresorhus/awesome/pull/2453#issuecomment-1365686751), [#2465](https://github.com/sindresorhus/awesome/pull/2465#issuecomment-1366292048), [#2418](https://github.com/sindresorhus/awesome/pull/2418#pullrequestreview-1230586435), [ #2435](https://github.com/sindresorhus/awesome/pull/2435#pullrequestreview-1239212521) and [#2394](https://github.com/sindresorhus/awesome/pull/2394#pullrequestreview-1230445990).
I've also followed the guidelines and checked project with …
=> Add Certificates

readme.md
https://github.com/MyHoneyBadger/awesome-github-wiki#readme
Project documentation is a vital part of project management that why this list can be considered as list a good documentation examples on GitHub
My reviews:
https://github.com/sindresorhus/awesome/pull/2382
https://github.com/sindresorhus/awesome/pull/2316
https://github.com/sindresorhus/awesome/pull/2335
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the …
=> Add GitHub Wiki

readme.md
https://github.com/readthedocs-examples/awesome-read-the-docs#readme
There's a lot of stuff going on in the field of documentation and technical writing. Especially the world of academic writing and research engineering is moving closer to software engineering and software documentation. Whatever documentation project you are writing, you can get inspired from a rapidly developing world of themes, framework extensions, structure, writing style etc.
There's a lot of reasons why a documentation project might be interesting. Those reasons might not strike the reader by simply visiting the project. So we try to give a few tips in the description about what makes a particular project interesting.
Another reason that these projects are interesting to share is that _not_ just that the end-result …
=> Add Read the Docs

readme.md
**https://github.com/thoughtspile/awesome-tiny-js#readme**
This is a list of small frontend libraries — mostly under 2Kb, with exceptions for select categories. Smaller frontend libraries help you build smaller apps, resulting in better user experience and fewer wasted resources. Apart from production usage: 
- A well-organized list of small libraries helps open-source developers focus their efforts on fields that are not already well-covered. 
- The cruft-free code of small libraries is an excellent learning material to understand how a class of libraries works — e.g. [hyperapp source](https://github.com/jorgebucaran/hyperapp/blob/main/index.js) is a great overview of virtual DOM.
- Many people put considerable effort into engineering size-conscious libraries, and deserve recognition for …
=> Add Tiny JS

readme.md
**https://github.com/Matthias84/awesome-flying-fpv**
**Open and DIY RC / FPV hard- and software. This topic is currently not refered and other existing lists are very limited **
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to …
=> Add flying-fpv

readme.md
This project lints correctly:
```
$ npx awesome-lint
✔ Linting
$
```
and has been out there for 30 days. Let's get it into the list! :)
**https://github.com/satta/awesome-suricata#readme**
This list contains resources in support of Suricata, a Free intrusion detection/prevention system and Network Security Monitoring engine. Suricata is a state of the art software tool that is used by many organizations, and that has spawned an active community of users and developers providing software, information and rulesets to support Suricata's mission.
As a member of that community, I compiled this list to gather these resources and create some visibility for the awesome projects out there!
My 2 reviews:
* https://github.com/sindresorhus/awesome/pull/2391#issuecomment-1352326001
* …
=> Add Suricata

readme.md
**[Awesome Game Production](https://github.com/vhladiienko/awesome-game-production#readme)**
**This list collects awesome resources for game producers specifically (sometimes oversimplified as Project Managers in game development), as leading a game production process requires numerous skills and knowledge in a whole variety of areas.**
Reviewed PRs:
- https://github.com/sindresorhus/awesome/pull/2470 ([comment](https://github.com/sindresorhus/awesome/pull/2470#issuecomment-1402636074))
- https://github.com/sindresorhus/awesome/pull/2503 ([comment](https://github.com/sindresorhus/awesome/pull/2503#issuecomment-1410874206))
- https://github.com/sindresorhus/awesome/pull/2502 ([comment](https://github.com/sindresorhus/awesome/pull/2502#issuecomment-1410880202))
- …
=> Add Game Production

readme.md
**https://github.com/stevinz/awesome-game-engine-dev**
**Resources geared toward development of high-level, fully featured game engines. For curious minds or those interested in game engine development.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a …
=> Add Game Engine Development

readme.md
https://github.com/airscripts/awesome-steam-deck
This awesome list contains all the resources, spacing from software and hardware, suggested for Steam Deck's ecosystem.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint violation are allowed, but does **not** count as a review.
- ✅ `Add …
=> Add Steam Deck

readme.md
**url to list**: https://github.com/hyperupcall/awesome-mastodon
**explanation**: Mastodon is a very popular decentralized platform for hosting a social networking platform. It's built on top of ActivityPub and has cemented it's legacy as an alternative social media platform since the hostile takeover of Twitter last year.
This does not add a new list; it updates the link to Awesome Mastodon. Unicorn.
~~The hueyy fork is reasonably popular and seems to be actively maintained.~~ 
I was somewhat confused since the PR template implies all PRs are requests for new awesome lists. Which means this pull request title is apparently invalid. I wasn't sure if reviews  were necessary in this case (looking at #2459 for instructions), so I did it anyways:
Try to prioritize unreviewed PRs, but you can …
=> Update link to Awesome Mastodon

readme.md
https://github.com/DevOpsHiveCloud/awesome-kustomize
[Kustomize](https://kustomize.io/) introduces a template-free way to customize Kubernetes manifests. It's extensible and uses a purely declarative approach to configuration customization, which will help you efficiently manage your Infrastructure as a code (IaC).
Kustomize is one of the [official](https://kubectl.docs.kubernetes.io/references/kustomize/) tools for managing Kubernetes resources, and this list will be the entry point for anyone to learn about Kustomize.
- https://github.com/sindresorhus/awesome/pull/2571#issuecomment-1501472676
- https://github.com/sindresorhus/awesome/pull/2736#issuecomment-1667879608
- https://github.com/sindresorhus/awesome/pull/2737#issuecomment-1667869111
- ✅ `Add Software …
=> Add Kustomize

readme.md
**https://github.com/MartinZikmund/awesome-uno-platform**
The list gathers most useful resources for developers working with Uno Platform.
**Reviewed PRs**
- https://github.com/sindresorhus/awesome/pull/2509#issuecomment-1463688010
- https://github.com/sindresorhus/awesome/pull/2482#issuecomment-1463745158
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or …
=> Add Uno Platform

readme.md
Minor naming fix: Google Cloud Platform -> Google Cloud.
=> Fix Google Cloud name next to Firebase

readme.md
https://github.com/virtualroot/awesome-opentofu#readme | [https://awesome-opentofu.com/](https://awesome-opentofu.com/)
> A refined list of OpenTofu resources and tools.
OpenTofu is an open-source and community-driven fork of Terraform that lets you define infrastructure as code. It has grown steadily since its inception 6 months ago, and I believe now is a good time to bring more exposure to it as a promising alternative to the non-open-source Terraform.
* https://github.com/sindresorhus/awesome/pull/2925#discussion_r1497578664
* https://github.com/benallfree/awesome-pocketbase/pull/36
* https://github.com/sindresorhus/awesome/pull/2966#issuecomment-1957326728
* …
=> Add OpenTofu

readme.md
**https://github.com/infosecB/awesome-detection-engineering**
**This is a list of resources intended specifically for cybersecurity threat detection engineers and blue teams. It's a one stop shop that has gained popularity amongst cyber defense professionals and is frequently updated and maintained. Thanks for the consideration.**
- https://github.com/sindresorhus/awesome/pull/2753
- https://github.com/sindresorhus/awesome/pull/2825
- ✅ `- [Framer](…) - …
=> Add Detection Engineering

readme.md
**https://github.com/benallfree/awesome-pocketbase**
**This list provides documentation, resources, guides etc. for the open-source Go-based backend PocketBase**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments …
=> Add PocketBase

readme.md
**[https://github.com/gokayfem/awesome-vlm-architectures](https://github.com/gokayfem/awesome-vlm-architectures)**
**This repository is a curated list focusing on the complexity and evolution of Vision Language Models (VLMs), addressing the challenge of navigating through numerous research papers to understand how different architectures vary. It aims to simplify the learning curve.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be …
=> Add VLM Architectures

readme.md
https://github.com/0pandaDEV/awesome-windows
This list is about awesome tools and apps for windows the goal is to replace its predecessor Awesome-Windows/Awesome which has not been updated in 3 years and recently vanished from GitHub.
My pull request reviews:
https://github.com/sindresorhus/awesome/pull/3223#pullrequestreview-2334849911
https://github.com/sindresorhus/awesome/pull/3223#pullrequestreview-2334850471
https://github.com/sindresorhus/awesome/pull/3210#pullrequestreview-2334852554 …
=> Add Windows

readme.md
**https://github.com/lutzh/awesome-event-driven-architecture#readme**
**A curated list of awesome articles and resources to learn about event-driven architecture.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments …
=> Add Event-Driven Architecture

readme.md
https://github.com/seifrajhi/awesome-cilium
I have created a dedicated awesome list about Cilium, which is an eBPF-based Networking, Security, and Observability. I thought it could be great being linked from here.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out …
=> Add Cilium

readme.md
**https://github.com/xavidop/awesome-firebase-genkit**
**Explain what this list is about and why it should be included here**
Awesome list with all things related to the new Firebase Genkit framework
- https://github.com/sindresorhus/awesome/pull/3146
- https://github.com/sindresorhus/awesome/pull/3129
- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
- ❌ `- [iOS](…) - Resources and tools for iOS development.`
- ❌ `- [Framer](…)`
- ❌ `- …
=> Add Firebase Genkit
