sindresorhus/awesome

- readme.md
A collection of hash functions, ciphers, tools, libraries, and materials related to cryptography.
> Add "Cryptography"

- readme.md
Please conform whether Misc is the right place to add this
> Added awesome boilerplates and projects .

- readme.md
I created a JSON variant of this meme.
> Add awesome-json.

- readme.md
* https://github.com/sbilly/awesome-security
> Adds awesome-security

- readme.md
Added awesome-flask under backend development.
URL: https://github.com/humiaozuzu/awesome-flask
> Adding Flask

- readme.md
The repo is considered to be the defacto awesome list for laravel - it's updated more frequently than the one being replaced...also 850+ stars!
> Changed link to Awesome Laravel

- readme.md
[Meteor.js Awesome](https://github.com/gillesfabio/awesome-meteor)
> added meteor-awesome

- readme.md
adds a up-to-date list of posts, repos, tutorials, slides, videos etc relating to the BEM naming convention.
> adds BEM resources page

- readme.md
I wasn't sure if I should create a "Design" section for this, so I just placed it in Miscellaneous section.
> Add Awesome Sketch list

- readme.md
A useful collection of web typography resources
> Added a link to "Web Typography"

- readme.md
I created a new repository that contains the list of awesome (not necessarily technology-related) blogs across the Internet. I had already added a dozen of entries to this list, so I think that it is appropriate to include it in this list.
> Added awesome-blogs to the list

- readme.md
Not sure if it has enough content for now.
I will contribute to this list regularly if the owner of the list allows it.
> awesome-atom to the list of editors

- readme.md
(Aside: I had to reread this commit title three times to make sure I had my grammar right.)
> Add Application Security list to Security list

- readme.md
Added [Codeface](https://github.com/chrissimpkins/codeface), a comprehensive list of fonts for text editors/source code and repository of the font binary files to the Resources list
> added Codeface text editor font list to Resources links

- readme.md
kahun's last update to this repository was 8 months ago. n1trux is much more active.
> awesome-sysadmin liked here is no longer maintained. But there's an alternative

- readme.md
Adding awesome deep vision - deep learning for computer vision.
> Awesome Deep Vision

- readme.md
Language homepage: http://crystal-lang.org
Source code: https://github.com/manastech/crystal
> Add Crystal programming language

- readme.md
Hi, this PR would add a new list I've started curating that tracks high quality open sourced production apps for web, desktop, and mobile. For myself I often want to see how non-trivial quality software is built usually using a particular stack and hope this might be useful to other developers.
> Add FOSS Production Apps

- readme.md
I've just made a page for the Dropwizard framework
> added awesome-dropwizard to back-end development

- readme.md
[Open Source Photography](https://github.com/Syskaw/awesome-OpenSourcePhotography)
open source software for photography : camera firmware mods, raw editors and also video tools.
> Add awesome-OpenSourcePhotography

- readme.md
Please let me know if something is wrong.
> Add awesome-opengl list

- readme.md
Would be awesome if you would add [awesome-AMA-answers](https://github.com/stoeffel/awesome-ama-answers)
Thanks
> adds awesome-ama-answers

- readme.md
https://github.com/feross/awesome-standard
> Add "Awesome Standard"

- readme.md
For Common Lisp: https://github.com/CodyReichert/awesome-cl
Awesome-cl was added (https://github.com/sindresorhus/awesome/commit/8236f1a0feda0aa69273f1088234e69b28362a04), then removed (https://github.com/sindresorhus/awesome/commit/c498a389169e49f049f44f97cc0cabec3621dc5c), and now hopefully re-added to the list.
I've taken over maintenance on the repo and moved it back to GitHub.
> Add awesome-cl

- readme.md
some useful stuff about [GraphQL](https://github.com/facebook/graphql)
> add awesome-graphql

- contributing.md
- create-list.md
- readme.md
> Attempt at separating out creating list vs contributing a list #266

- readme.md
https://github.com/git-tips/tips
This list is similar to Git Cheat Sheet but I think it lists something that don't exist in Git Cheat Sheet.
> Add Git Tips

- readme.md
A collection of awesome transit projects. This includes a variety of APIs, apps, visualizations, resources, and libraries for consuming transit data.
https://github.com/luqmaan/awesome-transit
:bus:
> Add awesome-transit

- readme.md
I've added awesome-watchos under Platforms,
Is this list mature enough to to be merged?
> Added awesome-watchos

- readme.md
Added emails to Front-end Development.
> Add Emails

- readme.md
- [Research Tools](https://github.com/emptymalei/awesome-research)
added to Miscellaneous
> Added a awesome list for Doing Research:

- readme.md
It's been more than a month since I submitted this list, it has grown a bit.
> Add data visualization

- readme.md
https://github.com/vinkla/awesome-share-links
> Add awesome share links

- readme.md
This patch adds awesome-jquery list. This time I've gone through the awesome manifesto and followed all the practices and requirements mentioned there. Thank you for considering merging it to the awesome repository also.
> Awesome jQuery

- readme.md
Neo4j awesome list now is stable. We got support from Neo4j comunnity and Neo Technology itself.
> Add awesome-neo4j list.

- create-list.md
> Added clarification

- readme.md
Internet of Things becomes a major field nowadays in software and hardware engineering, and the number of existing resources associated with this domain becomes *huge*.
As such, I felt it was a good idea to create a curated list of awesome projects and resources related to this domain.
> Added Internet of Things

- contributing.md
I added a section on how to update a Pull Request, because I often run across issues with contributors not knowing how to amend a commit and force push to their PR. This post should help that, and since it is also on a GitHub repo, it can be edited and made into a definitive guide for maintainers to use to help new gitters. See this issue for rationale: https://github.com/sindresorhus/awesome-scifi/pull/174
Also added a TOC because the Contribute file is getting a bit long.
> Add section on how to update a pull request

- readme.md
This can be confirmed by either a Google search (see the result count for both) or from the second list item.
A developer environment is different from a development environment as the first is a synonym for an office and the latter indicates something closer to a piece of software that aims to ease development.
> Developer environment should be development env.

- readme.md
Created with https://github.com/dkhamsing/frankenstein
> fix redirect

- readme.md
Since this list did not nearly as attraction as I thought it would, I don't think that it deserves the right to be called awesome any more.
**NOTE:** The only reason I'm submitting the removal of the list is because I'm the author, the only contributor, and the only maintainer of this list at the moment. If it weren't mine, I wouldn't even think about removing it.
> Removes awesome blogs

- readme.md
https://github.com/loverajoel/jstips
> Add JavaScript Tips

- readme.md
https://github.com/fukuball/Awesome-Laravel-Education/blob/master/langs/en_US.md
> Add Laravel Education

- readme.md
Hi,
`awesome-neo4j` is migrated from GraphGeeks to Neueda4j. I am updating link.
> Neo4j - repository migrated to another organization

- readme.md
I'm not sure if "Learn" is the right section for computer history videos and texts. I considered the "Miscellaneous" section as well, but since this list have lot of learning material and since we should always learn from history, I added it here. Let me know if you have a better place for it :smiley:
> Add Computer History

- readme.md
Vulkan is the new graphics API.
> Add link to awesome-vulkan

- readme.md
> Fixed spelling

- readme.md
Some MongoDB lists exist already, but they aren't referenced here, aren't maintained, and aren't complete at all anyway (see #477), so I decided to give it a try. :+1: 
https://github.com/ramnes/awesome-mongodb
> Add MongoDB

- awesome.md
I hope that was not there on purpose given "Ensure your list is grammatically correct, typo free and has no Markdown formatting errors. This should also apply to pull requests."
> DOC: Fixed minor but glaring grammar error

- readme.md
Delete one with italics according to style of others.
-
Closes #634.
> Delete dublicate LaTeX link

- readme.md
An awesome list of all things RethinkDB
> Add RethinkDB

- readme.md
This is a [funny collection of Markov chain output](https://github.com/sublimino/awesome-funny-markov).
I've attempted to comply with the manifesto and contribution guidelines (thanks for maintaining such a huge list). 
I believe this is applicable to the `awesome-list` concept as funny Markov chains are an integral part of computer history, sitting at the rare intersection of technology and laughter. A [history](https://github.com/sublimino/awesome-funny-markov/blob/master/README.md#a-history-of-funny-markov-chains) section is included.
> Add Funny Markov

- readme.md
> An Observable is a collection that arrives over time. Observables can be used to model push-based data sources such as events, timer intervals, asynchronous requests, and animations. Observables can be transformed, combined, and consumed using array-like methods.
https://github.com/sindresorhus/awesome-observables
> Add JavaScript Observables

- readme.md
Hi there,
First of all, thanks for this awesome list!
I just saw that PostCSS is missing, so I added it.
Have a nice day!
> Add PostCSS

- readme.md
https://github.com/gitfrage/guitarspecs
This is a "top-down checklist" for the assembly of a solid-body electric guitar. 
It can help you to build a guitar with specific sound and playability characteristics.
> Add Electric Guitar Specifications

- readme.md
Adds a curated list of [Awesome Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics) software, resources, and libraries used in analyzing various genomics data.
/cc: @danielecook
> Add Bioinformatics

- readme.md
As suggested by @egeerardyn, the Awesome Windows repository (for reference - #671) is shifted to an organization and all the necessary suggestions, changes has been made. It is ready to be included in the awesome list.
> Changed Awesome Windows URL

- readme.md
**[Apache Wicket](https://github.com/PhantomYdn/awesome-wicket)**
**[Explain what this list is all about and why it should be included here.]**
Apache Wicket is powerful back-end framework and has its own good community. It will be awesome to share this great tool with other java back-end developers.
> Add Apache Wicket

- readme.md
**[URL to the list here.]**
**[Explain what this list is all about and why it should be included here.]**
The F in ColdFusion needs to be capitalized.
> fix a typo for the product ColdFusion

- readme.md
**https://github.com/TalAter/awesome-progressive-web-apps**
A curated list of only the best learning resources, reference material, videos, tutorials and case studies for progressive web apps.
**I know this repo is less than 20 days old, but I have actually been working on this list as research for my book for the past 4 months. I have read every single article on the list (and many others) and only included the best.**
> Add Progressive Web Apps

- readme.md
**https://github.com/vert-x3/vertx-awesome**
**Vert.x Awesome is an list of awesome frameworks, libraries or other components for use with or that use Vert.x version 3. This list will help other Java back-end developers.**
> Add Vert.x

- create-list.md
Hi @sindresorhus,
I think it would be very nice to propose a naming convention (`awesome-listName`) for anyone that makes a new **awesome** list. This would help to find lists easier and thereby prevent duplications.
Looking forward to your feedback.
Best wishes
[removed remainder as it does not apply to this PR]
> add naming convention for new lists

- readme.md
**https://github.com/xen0l/awesome-dtrace / http://awesome-dtrace.com**
DTrace is a dynamic tracing framework, which allows safe observation of productions systems. Over the time, many programming languages, operating systems and frameworks added support for various DTrace probes and made problem troubleshooting available via DTrace. DTrace is a wonderful tool and more people should know about it and use it.
> Add DTrace

- readme.md
UserScripts can improve browsing experience a lot, and I really missed an awesome list when searching for new scripts.
PR to include https://github.com/brunocvcunha/awesome-userscripts
Thanks!
> Add Userscripts

- readme.md
**[https://github.com/tobiasbueschel/awesome-pokemon]**
**[Awesome-pokemon is a curated list of awesome Pokemon & Pokemon Go resources, tools and more. It should be included because a lot of Pokemon related development is currently happening in the community see e.g. [/r/pokemondev](https://www.reddit.com/r/pokemongodev) and this list helps to collect all helpful resources.]**
> Add Pokémon

- pull_request_template.md
i replaced "dot" with "period" for proper wording
> updated pull request template for proper wording

- readme.md
https://github.com/sobolevn/awesome-cryptography
`awesome-cryptography` is all about cryptography and encryption.
It has all started with [this issue](https://github.com/sindresorhus/awesome/issues/663). I have requested a new list about `encryption`, soon I have found [`retter`](https://github.com/MaciejCzyzewski/retter), which seemed to be an `awesome-cryptography` list. 
With all the respect to the author, his great work, and the content itself, `retter` is not an `awesome-list`. It is a collection of different implementations of cryptography algorithms in `C`, and a structured folder of bookmarks.
That was an original reason I have started my own list. But, I can also add the fact `retter` was not updated for 10 month now.
Things I have improved in my list:
I have not found any …
> Changed "awesome-cryptography" link

- readme.md
**https://github.com/bnb/awesome-hyperterm**
`awesome-hyperterm` is a list of awesome plugins, themes, and resources for the Hyperterm app, which is an electron-based terminal that's insanely extensible and (subjective) just really damn awesome (/subjective).
Adding the `awesome-hyperterm` (https://github.com/bnb/awesome-hyperterm) list to the `Development Environment` section of Awesome lists!
> Add HyperTerm

- readme.md
**[https://github.com/SrinivasanTarget/awesome-appium]**
**[A curated list of delightful Appium resources. Appium is an open source, cross-platform test automation tool for native, hybrid and mobile web apps, tested on simulators (iOS, FirefoxOS), emulators (Android), and real devices (iOS, Android, Windows, FirefoxOS).]**
https://github.com/SrinivasanTarget/awesome-appium
> Add Appium

- readme.md
**https://github.com/HollyAdele/awesome-programming-for-kids**
**Resources to teach programming to adults are very different from ones useful for teaching the basics to children.  Awesome lists of resources for adults are already on the Awesome list; here is a list of the best I've found for children.**
> Add Programming for Kids

- readme.md
I create the awesome-dotnet-core collection, that includes all the frameworks, libraries, and resources of .NET core 1.0 that just released by Microsoft in June in this year.  
Please help me to update it into the awesome collection. Thank you very much!
-
> Add .NET Core

- readme.md
https://github.com/dylanrees/toolsforcitizenscience
This list contains a large collection of tools for citizen scientists.  I couldn't find a list similar to it, especially on GitHub; hence my desire to create it.  It's got a open-source software section, which GitHub users in particular should be useful in building, but it also lists resources such as publications, open-source equipment suppliers, physical spaces that are practicing citizen science, and a few other things.
> Add Citizen Science

- readme.md
**https://github.com/jaredmichaelsmith/awesome-vehicle-security**
**This list contains the most relevant resources for learning and practicing vehicle security research, car hacking, and reverse engineering of vehicles. The community is rather small now and vehicle security is an emerging field, but I wanted to jump in early and provide this resource to those wanting to jump right into the field.
Note, this list has *not* been around for at least 20 days, but was created yesterday from my own previous list of resources, but I wanted to go ahead and get this in the system in case you find other bugs :)
**
Find it at: [https://github.com/jaredmichaelsmith/awesome-vehicle-security](https://github.com/jaredmichaelsmith/awesome-vehicle-security).
> Add Vehicle Security and Car Hacking

- readme.md
**[https://github.com/jagracey/Awesome-Unicode](https://github.com/jagracey/Awesome-Unicode)**
**Unicode is undervalued and poorly understood. I've contributed a curated list of delightful Unicode tidbits, qwirks, packages and resources.**
*Given that Unicode is poorly understood, I've included a few sectional explanations prior to some lists, which may or may not violate the spirit of requirement #4.*
- [~] only has awesome items with descriptions *(Awesome lists are curations of the best, not of everything)*,
…sources.
https://github.com/jagracey/Awesome-Unicode
> Add Unicode

- readme.md
**[exAspArk/awesome-chatops](https://github.com/exAspArk/awesome-chatops)**
`awesome-chatops` is a collection of awesome bots for ChatOps. ChatOps is a collaboration model that helps to connect people, process, tools, and automation into a transparent workflow (conversation-driven development). 
> Add ChatOps

- readme.md
A complete and curated list about the original 1989 Game Boy handheld console.
Everything available to start studying the hardware/software mechanism, create a working ROM, an emulator or simply play with the console architecture.
---
> Add Game Boy Development

- readme.md
**https://github.com/d3viant0ne/awesome-webpack**
**`awesome-webpack` is a list of awesome plugins, themes, and resources for the Webpack bundler maintained by people passionate about Webpack as a tool. It contains a broad range of content from plugins & loaders to learning materials. Content is vetted for the appropriate level of awesome & additions to the list are linted with `awesome-lint` via `Travis`**
> Add Webpack

- readme.md
**https://github.com/kdeldycke/awesome-falsehood**
**"Falsehood" articles are a form of commentary on a particular subject, and are appreciated by the developer community at large for their effectiveness and density. They're a convenient written form to approach an unfamiliar domain by dispelling myths, point out common pitfalls, show inconsistencies and subtleties.**
> Add Falsehood

- readme.md
**https://github.com/springload/awesome-wagtail**
**This list is about [Wagtail](https://wagtail.io/), a popular CMS in the Python/Django communities. Wagtail encourages the development of third-party plugins/apps/packages, and this list is a good way to keep track of the ones that are the most interesting (along with other community resources).**
> Add Wagtail

- readme.md
**[URL to the list here.]**
https://github.com/stevemao/awesome-git-addons
**[Explain what this list is all about and why it should be included here.]**
A curated list of addons that extends/enhance the git cli.
I'd like to add a simple description since "add-ons" might not be very clear what it is.
> add a description to "Git Add-ons"

- readme.md
[https://github.com/heynickc/awesome-ddd](https://github.com/heynickc/awesome-ddd)
A curated list of Domain-Driven Design (DDD), Command Query Responsibility Segregation (CQRS), Event Sourcing, and Event Storming resources.  It contains books, training courses, video collections, mailing lists and forums, blogs, sample projects, libraries and frameworks, podcasts and interviews, and user groups related to the aforementioned software architecture concepts.
> Add Domain-Driven Design

- readme.md
**https://github.com/willempienaar/awesome-quantified-self**
**Awesome Quantified Self: Websites, resources, devices, wearables, applications, and platforms for self tracking.**
Adding a link to the awesome quantified self repository: https://github.com/willempienaar/awesome-quantified-self
> Add Quantified Self

- readme.md
**https://github.com/ungoldman/awesome-browserify**
**A curated list of awesome Browserify resources, libraries, and tools.**
> Add Browserify

- readme.md
https://github.com/vinkla/awesome-edutainment
A curated list of awesome gamification to learn editors, languages, programming, etc.
> Add Educational Games

- readme.md
**[https://github.com/nirgn975/awesome-drupal](https://github.com/nirgn975/awesome-drupal)**
**A collection of awesome Drupal resources to learn Drupal and it's modules.**
> Add Drupal

- readme.md
**https://github.com/nicolesaidy/awesome-web-design**
**A curated list of awesome resources for digital designers.**
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at the bottom of the …
> Add Web Design

- readme.md
Follow-up from #783, with addressed feedback.
**https://github.com/janikvonrotz/awesome-powershell**
**PowerShell is a cross-platform object-oriented shell and scripting language. It was originally developed by Microsoft for Windows and went open-source and cross-platform in 2016. This list contains a delighful packages and resources for PowerShell**
--------------------------
PowerShell team and community spent a lot of time contributing to the list in the [past few months](https://github.com/janikvonrotz/awesome-powershell/issues/2). We think it's pretty solid right now and we hope it would serve as a useful community resource for people who recently start look into PowerShell. 
Also, PowerShell has it's 10th Anniversary on Monday, November 14th. 🎉 🎉 🎉
> Add PowerShell

- create-list.md
Changed from `20` to `30`days because the [pull request template](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) says 30 days.
Damn. Can’t wait to submit https://github.com/micromata/awesome-javascript-learning-resources 😗
> Update amount of days before submitting a list

- readme.md
**https://github.com/websemantics/awesome-ant-design**
**Ant Design is a fairly new and popular UI framework (5k+ stars on Github) with tools, implementation ins in react and vue.js, for mobile and web apps. This works as an alternative to [Bootstrap](http://getbootstrap.com/), [Semantic-UI](http://semantic-ui.com/) or Github [Primer](https://github.com/primer/primer)**
- [x ] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- [ x] This pull request has a descriptive title. _(For example: `Add Node.js`)_
- [x ] **has been around for at least 20 days,**
- [ x] is a non-generated …
> Add Ant Design

- readme.md
**https://github.com/hbokh/awesome-saltstack**
**"Salt is a new approach to infrastructure management built on a dynamic communication bus. Salt can be used for data-driven orchestration, remote execution for any infrastructure, configuration management for any app stack, and much more."  
This is a new list about Salt / SaltStack, added under a NEW section named "IT automation tools".  
A section like that was missing and other future awesome-lists (e.g. about Puppet, Chef, Ansible, etc.) can be set up under this section.**
Added a new section with a new awesome list "Awesome SaltStack".
Other awesome lists to be placed here in the future could be about Puppet, Chef, Ansible, etc.
> Add SaltStack

- readme.md
**https://github.com/aliesbelik/awesome-jmeter**
**Adding [Apache JMeter](http://jmeter.apache.org/) related curated collection, that includes all the plugins, integration capabilities, testing techniques, learning resources, best practices used for load-testing and performance measurement activities using this application.**
> Add JMeter

- readme.md
**https://github.com/harpribot/awesome-information-retrieval**
**Information Retrieval and Web Search is a field which involves finding relevant information for a given query, be it for as simple as a database search, or as complicated as a web search (Eg - Google, Bing, Yahoo). There has been renewed interest in this field, thanks to Deep Learning and Vector Space Modeling. Finding content that is both relevant to the user, and has high topic relevance is the key point of research in this field. However, many don't know about the different resources available at out disposal. It would be a good idea to have a list of Awesome Information Retrieval and Web Search, for people to discover resources and make this field even more awesome.**
Failure to properly do so will just result in the …
> Add Information Retrieval

- readme.md
**https://github.com/sger/ElixirBooks**
**List of books about Elixir programming language**
> Add Elixir Books

- readme.md
https://github.com/monostable/awesome-electronics
This is a list of sites, software and services for electronic engineers and hobbyists. 
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and should be added at …
> Add Electronics

- readme.md
Will rebase this on master after #865 is merged.
> Add Hardware category

- readme.md
**https://github.com/terkelg/awesome-creative-coding**
**It can be hard to get started with more advance creative coding. This is a list of beginner-friendly tools, resources and things to get you started**
- The entry in the Awesome list should include a short description about …
> Add Creative Coding

- readme.md
**https://github.com/petk/awesome-jquery and https://github.com/petk/awesome-dojo**
**This is a minor patch that only fixes two existing repositories locations**
- The entry in the Awesome list should include a short description about the list project/theme (not the list …
> Rename jQuery and Dojo repositories locations

- readme.md
References #550 
I noticed that there were quite a few resources related to these three topics in the misc section so this organised them a bit.
As this is a fairly big change, would look for some feedback based on this.
> Create Business, Work and Networking sections

- readme.md
**https://github.com/aviaryan/awesome-no-login-web-apps**
**It is a curated list of awesome web apps that work without requesting you to create an account. This list will help users to do common tasks without having to download a software or create web accounts.**
PS - I have not added a banner image to the list yet, the reason being I am not good in design. I would love a PR about it. I am still going on with this PR because I saw some lists in this list of lists without a logo/illustration. 
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the …
> Add No-Login Web Apps

- readme.md
Should match all guidelines.
**https://github.com/TheJambo/awesome-testing**
**Software Testing resources and tools. Nothing like this except language-specific ones with developers in mind on your list currently.**
- The entry in the Awesome list should include a short …
> Add Testing

- readme.md
**https://github.com/johnjago/awesome-free-software**
**This is a list of common programs (as opposed to the other two FOSS lists which focus more on development tools) that have a Free Software Foundation approved license. The purpose of this list is to give users the ability to quickly find the best free software alternatives for many categories of applications.**
> Add Free Software

- readme.md
I'd like to add a curated list of deep learning papers. Thank you.
> Add Deep Learning Papers

- readme.md
**https://github.com/podo/awesome-framer**
**Curated list of Framer prototyping tool articles, resources, tutorials, modules and videos for beginners and more advanced users.**
- The entry in the Awesome list should include a short description about the list project/theme (not …
> Add Framer

- readme.md
https://github.com/BubuAnabelas/awesome-markdown/
**Markdown has been arround for a long time and it's becoming widley used among web-devs and bloggers. This list contains useful and delighful resources for Markdown**
- The entry in the Awesome list should include a short …
> Add Markdown

- readme.md
the latest version of angular prefers to just be called `angular`, as the version increases every 6 months, while the original one remains with `JS` appended
**[Insert URL to the list here.]**
https://github.com/AngularClass/awesome-angular
**[Explain what this list is about and why it should be included here.]**
repo renamed
- This pull request has a descriptive title. For example, `Add Name of …
> Use correct names for both versions

- readme.md
https://github.com/quangv/awesome-couchdb
This is an awesome curated resources list for CouchDB. CouchDB is one of the first document NoSQL databases.
- The entry in the Awesome list should include a short description about the list project/theme (not the list itself), and …
> Add CouchDB

- readme.md
**https://github.com/mislavcimpersak/awesome-dev-fun**
**This is a list of funny, whimsical and mostly useless scripts/packages from which developers can get a good laugh.**
- The entry in the Awesome list should include a short description about the list project/theme (not the …
> Add Dev Fun

- readme.md
**[https://github.com/armaldio/awesome-construct](https://github.com/armaldio/awesome-construct)**
**A curated list of tools, tutorials, examples, and much more, for the awesome game development engine Construct 2. Edit**
- The entry in the Awesome list should include a short …
> Add Construct 2

- readme.md
This PR adds **Awesome Web Security** list.
**[https://github.com/qazbnm456/awesome-web-security](https://github.com/qazbnm456/awesome-web-security)**
**A curated list of Web Security materials and resources.**
- The entry in the Awesome list should include a short description …
> Add Web Security

- readme.md
**https://github.com/ooade/awesome-preact**
**It's a curated list of amazingly awesome things regarding Preact ecosystem.**
- Include a short description about the list project/theme. It should not describe the list itself.<br>Example: `- [Fish](…) - User-friendly shell.`
- Be added at …
> Add Preact

- readme.md
**[https://github.com/awkward/awesome-netherlands-events](https://github.com/awkward/awesome-netherlands-events)**
**This list contains awesome (tech related) events happening (and are mostly recurring) in The Netherlands like: conferences, meetups and parties 🎉**
- The entry in …
> Add Events in the Netherlands

- readme.md
**https://github.com/jbmoelker/progressive-enhancement-resources**
**A comprehensive collection of resources on Progressive Enhancement. From concept and strategies to feature detection and testing methods. Complete with a list of (code) examples.**
~~A few notes:~~
- ~~Collection has a Table of Contents section, but it's named `Table of Contents`, not `Contents`.~~
- ~~Items are formatted consistently, but descriptions start with a lowercase.~~
- ~~Collection does not have the Awesome badge yet as I figured I'd only add this when the list is accepted.~~
~~Willing to change the above if needed.~~
- I have read and understood the …
> Add Progressive Enhancement

- readme.md
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - …
> awesome-rust is now at rust-unofficial

- readme.md
https://github.com/kakoni/awesome-health
A curated list of awesome open health software, libraries, tools and resources. This guide is very nice for working professionals and healthcare providers looking for open source health solutions. I hope you consider adding it!
- The …
> Add Healthcare

- readme.md
Help vote it up: https://www.producthunt.com/posts/awesome-weekly
I'm planning a launch in 3 weeks. (Wanted to do earlier, but got busy with real life)
> Awesome Weekly is on Product Hunt

- readme.md
You will find the List **[here](https://github.com/DavidLambauer/awesome-magento2)**.
The Magento 2 Awesome List is about the eCommerce System Magento 2 which is built in PHP. The List collects hand-picked resources of extensions, themes, learning resources or other awesome Magento 2 related resources. All resources are reviewed by myself to make sure the quality of each submit is as high as possible. 
The List is quite young but it is growing pretty fast and was already published in the official Magento 2 Development Documentation. You will find the link here:
[Magento 2 Community Resources](http://devdocs.magento.com/community/resources/)
- I have read and understood the …
> Add Magento 2

- readme.md
> Add description to Atom entry

- readme.md
**https://github.com/victorlaerte/awesome-it-quotes**
**This is an list of awesome IT quotes. The aims is to get together all relevant quotes said over the history of IT. There's no much data yet, but I'm still selecting new ones.**
- The entry in the Awesome list should include …
> Add IT Quotes

- readme.md
> Add description to Node.js entry

- readme.md
**[https://github.com/k4m4/terminals-are-sexy](https://github.com/k4m4/terminals-are-sexy)**
> **A curated list of Terminal frameworks, plugins & resources for CLI lovers.**
GitHub Repo: [here](https://github.com/k4m4/terminals-are-sexy/)
**Project Site: [here](http://terminalsare.sexy/)**
(**NOTE**: I have included a [travis-ci](https://travis-ci.org/k4m4/terminals-are-sexy) badge, implemented to run with the [awesome_bot](https://github.com/dkhamsing/awesome_bot) for link validation purposes.)
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the …
> Add Terminals Are Sexy

- readme.md
**https://github.com/arbox/machine-learning-with-ruby**
**Libraries, projects and learning resources about Machine Learning done with Ruby**
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - …
> Add Machine Learning with Ruby

- readme.md
**https://github.com/motion-open-source/awesome-rubymotion**
**RubyMotion let's you write cross-platform apps for iOS, Android, tvOS, watchOS and OS X in Ruby. This awesome list has been around for 2 years now, and has 45 stars. This list tries to give a complete overview of resources about RubyMotion** 
-  The entry in the Awesome list should:
- The list I'm submitting complies with these requirements:
- Has a Table of Contents section.
- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
- Has consistent formatting and proper spelling/grammar.
- Go to the top and read it again.
> Add RubyMotion

- readme.md
**https://github.com/vitalets/awesome-smart-tv**
**Smart TV is growing platform with own ecosystem and main players like Samsung, LG, Android TV and Apple TV.**
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- …
> Add Smart TV

- readme.md
**https://github.com/sheonhan/awesome-effective-altruism**
**A new philosophical movement called Effective Altruism (EA) has reported success at addressing the problems with traditional methods of philanthropy. It's swiftly overcoming endemic inefficiencies of large charities. However, while nearly 22% of people who reported themselves as Effective Altruists are programmers, there is no existing programmatic work related to the movement. Awesome-Effective-Altruism hopes to be a platform to both expand the movement to a wider audience and vitalize the developer community to create projects and tools related to Effective Altruism.**
- I have read and understood the [contribution …
> Add Effective Altruism

- readme.md
**https://github.com/johnjago/awesome-ad-free**
**This is a list of online services, websites, applications, and publications that are not supported by advertising, allowing people to quickly find ad-free alternatives.**
- Include a short description about the project/theme of the list. …
> Add Ad-Free

- readme.md
Add Awesome-Esoteric, a curated list of esoteric programming languages
https://github.com/angrykoala/awesome-esoteric
This list contains esoteric programming languages and resources related to those languages.
It will contain only languages that are considered esoteric (a.k.a. not intended for maintream development) and are in some way interesting and different to other languages of the list. Languages without compiler/interpreter will be accepted as long as are properly documented.
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a …
> Add Esolangs

- readme.md
> Add description to CakePHP and Laravel entries

- readme.md
**https://github.com/meitar/awesome-lockpicking**
**A curated list of awesome guides, tools, and other resources related to the security and compromise of locks, safes, and keys.**
- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
- The image should link to the project website or any relevant website.
- The image should be high-DPI. Set it to maximum half the width of the original image.
> Add Lockpicking

- readme.md
Added this Awesome list to the Business Section: https://github.com/LappleApple/awesome-leading-and-managing.
**https://github.com/LappleApple/awesome-leading-and-managing**
**List of resources on leading people and being a manager. Geared toward software engineering, but potentially useful to anyone. Includes 15 sub-pages with lots of articles, videos, slide decks.**
- This pull request has a descriptive title.<br>For example, `Add Name of List`, …
> Add Leading and Managing

- readme.md
**[https://github.com/roaldnefs/awesome-prometheus](https://github.com/roaldnefs/awesome-prometheus)**
**Curated list of resources: tutorials, videos, articles about using Prometheus.**
- Include a short description about the project/theme of the list. **It should not describe the list …
> Add Prometheus

- readme.md
**https://github.com/stetso/awesome-gideros **
**This is a list of resources for the Gideros Game Engine which is a Lua-scripted C++-based engine with great support for plugins and a fast development workflow on mobile, desktop and web **
- Include a short description about the …
> Add Gideros

- readme.md
https://www.producthunt.com/posts/lungo
I've spent hundreds of hours for free working on this list. So I think it's ok to add this for a couple of days.
> Self-promotion

- readme.md
**https://github.com/hobbyquaker/awesome-homematic**
**Homematic is a series of Smart Home devices, especially popular in Germany. This list contains awesome open source projects that interface with Homematic.**
- Include a short description about the project/theme of the list. **It …
> Add Homematic

- readme.md
**https://github.com/Siilwyn/awesome-pixel-art**
**A curated list of amazingly awesome things regarding pixel art.**
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- …
> Add Pixel Art

- readme.md
**https://github.com/machinomy/awesome-non-financial-blockchain**
**The list contains non-financial applications of blockchain technology.**
Since it Ripple, and Bitcoin lists are into the same space, I dare to combine these three into a category "Decentralized Systems".
- Include a short description about the project/theme of the list. **It should not describe the list …
> Add Non-Financial Blockchain

- readme.md
https://github.com/sfischer13/awesome-ledger
Resources for the Ledger command-line accounting system.
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - …
> Add Ledger

- readme.md
The link www.github.com/hgupta9/awesome-actionscript3 simply redirects to robinrodricks so I have updated this in your awesome list to prevent a double redirect.
> Fix link for AS3 language

- readme.md
✨🍰✨
https://github.com/kennethreitz/awesome-coins/
This is an awesome list for crypto currency.
> Crypto Currency Tools & Algorithms

- readme.md
**https://github.com/likedan/Awesome-CoreML-Models**
**We collected the largest list of available models in Core ML format, so iOS developers can easily experience and compare different models.**
- Include a short description about the project/theme of the list. **It should not describe …
> Core ML Models

- awesome.md
> Fix spelling

- awesome.md
This PR only includes grammatical changes to the main awesome.md file. I'm not adding a new awesome list, just improving the awesome manifesto,
> Minor grammar enhancements to awesome.md

- readme.md
**https://github.com/guillaume-chevalier/awesome-deep-learning-resources**
**Hi there! I have built an "awesome list" on how to learn to do Deep Learning learning. I also give this list a more "personal" flavor where users can take my list as a template. By personalized, I mean that they put their name on it in a way that they have very carefully reviewed (and found useful) all the content they have listed on their own sub-list (like I did - only awesome things are found in my list). I encourage forks and contribution to the awesome ecosystem. Also, on top of all I believe that the subject of deep learning is important, just take a look at how much "Machine Learning" and "Deep Learning" are trendy compared to "Computer Programming" on the Google Trends, it's through the roof! And it is …
> Add Deep Learning Education

- readme.md
https://github.com/zachflower/awesome-open-source-supporters
The Open Source Supporters awesome list highlights companies that offer their tools and services for free to Open Source and public projects. It is important to note that some companies offer standard free tiers (such as Slack, for example), however this list focuses _specifically_ on companies that have made an overt commitment to the Open Source community.
- This pull request has a …
> Add Open Source Supporters

- readme.md
**https://github.com/siboehm/awesome-learn-datascience**
This list contains Data Science tutorials using Python. It is aimed at beginners. The list will be expanded, but I intend to keep it short and sweet in order to not overwhelm anyone. One link per important topic/subtopic. The links include resources that I found helpful and that were successfully used for many beginners at my Data Science student group.
- This pull request has a descriptive …
> Add Data Science Tutorials

- readme.md
**https://github.com/tleb/awesome-mastodon**
**This list aims at bringing together everything related to the Mastodon network, which describes itself as "the world’s largest free, open-source, decentralized microblogging network". ATM, the list contains documentation, clients, tools, bots and various accounts.**
- The entry …
> Add Mastodon

- readme.md
**[Awesome Design Principles](https://github.com/robinstickel/awesome-design-principles)**
A curated list of good design and experience principles.
Design Principles are a tool for creating better and more consistent designs and experiences. They are high level rules that guide detailed design decisions. They are often written down within bigger style guides, pattern libraries or design systems.
> Add Design Principles

- readme.md
Hi Sindre,
I appreciate the opportunity to sponsor the awesome list!!! This PR provides a hard-coded sponsorship for Code Sponsor.
Thanks!
Eric
> Replace Code Sponsor banner with a less obtrusive one

- readme.md
#928 
Added descriptions for Electron, Cordova, Xamarin, IPFS, Fuse, Heroku, Standard Style, Mad
Science npm Packages, Polymer and SVG.
Also modified description for A-Frame VR for clarity.
- Include a short description about the project/theme of the list. **It should not describe the …
> Add some descriptions

- readme.md
**https://github.com/mojoaxel/awesome-regression-testing**
***Regression Testing is an underestimated topic. This list tries to give an overview about the topic.***
- The list I'm submitting complies with these requirements:
- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
- The image should link to the project website or any relevant website.
- The image should be high-DPI. Set it to maximum half the width of the original image.
> Add Visual Regression Testing

- readme.md
**https://github.com/johnjago/awesome-theravada**
**This list contains a variety of resources on Theravada Buddhism, including academic articles, books, talks, communities, videos, and more. The goal of this list is to provide quick access to information on the Theravada tradition and to have this information presented in many forms. That way, it will be useful to people all people, whether they are looking for a place to start academic research or just learn about the religion.**
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a …
> Add Theravada

- readme.md
Adds descriptions for 11 entries in the list. Helps with #928.
- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md).
> Add descriptions for entries

- readme.md
repo location changed
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly …
> Correct link to Angular list

- readme.md
Adding `folkswhocode/awesome-diversity`, a curated list of amazingly awesome articles, websites and resources about diversity in technology.
[https://github.com/folkswhocode/awesome-diversity](https://github.com/folkswhocode/awesome-diversity)
- Include a short description about the …
> Add Diversity

- readme.md
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - …
> Update URL of the `Free Software Testing Books` list

- readme.md
https://github.com/shuaibiyy/awesome-terraform
A curated list of resources on HashiCorp's Terraform. Terraform enables and simplifies the practice of infrastructure-as-code.
- Include a short description about the project/theme of the list. **It should not describe the list …
> Add Terraform

- readme.md
PostCSS is not a preprocessor - https://github.com/jjaderg/awesome-postcss/edit/master/README.md
> Fix PostCSS description

- readme.md
This PR will resolve #1250.
Closes #1235
> Remove dead Effective Altruism link

- readme.md
fixes from [awesome_bot](https://github.com/dkhamsing/awesome_bot)
> Update outdated links

- contributing.md
- readme.md
I appended #readme to every link, where appropriate. 
Fixes #1227
> Append `#readme` to all awesome list links

- readme.md
https://github.com/miguelmota/awesome-amazon-alexa
Curated list of awesome resources for the Amazon Alexa platform.
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
- Be added at the bottom of the appropriate category.
- Either fullwidth or placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
- The image should link to the project website or any relevant website.
- The image should be high-DPI. Set it to maximum half the width of the original image.
- Should be placed on the right side of …
> Add Amazon Alexa

- readme.md
https://github.com/joho/awesome-code-review
List of code review tools, books, papers, talks etc. Code review is a very common engineering practice and there are lot of interesting resources going back ~40 years and new talks and tools coming out all the time.
- The list I'm submitting …
> Add Code Review

- readme.md
**https://github.com/ZYSzys/awesome-captcha**
**This repo is a curated list of awesome captcha libraries and captcha crack tools.**
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly …
> Add Captcha

- readme.md
[awesome-ffmpeg](https://github.com/transitive-bullshit/awesome-ffmpeg)
> A curated list of awesome ffmpeg resources with a focus on JavaScript.
FFmpeg is an extremely popular media editing tool that a lot of developers depend on.  I was pretty surprised to find that it didn't have an existing awesome list.
I have triple-checked the contributing guidelines and believe this list to be in conformance.
- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
- Be added at the bottom of the appropriate category.
- Either fullwidth or placed at the …
> Add FFmpeg

- readme.md
**https://github.com/frenck/awesome-home-assistant#readme**
This list is for Home Assistant. Home Assistant is an open source Home Automation system/hub which allows a user to automate every aspect of their home fully. It is currently the largest open source project in its category.
The list itself is now a month old and snowballed. It had some contributions and got a surprisingly large amount of stars on GitHub, which caused it to be a trending repository on GitHub in the month it was published.
> :speech_balloon: _I've tried to be as accurate as possible with this PR, by adding checkmarks and comments on each requirement in the PR template. I'm really curious to find out what you think!_
:white_check_mark: **Please read it multiple times. I spent a lot of time on these guidelines and …
> Add Home Assistant

- contributing.md
Small fix: "a awesome" to "an awesome"
💖
> Fix typo in `contributing.md`

- readme.md
I'm no longer interested in maintaining my list, and I don't think it is a useful inclusion here, as it is so stale that it is no longer awesome. 
Thanks. :)
> Remove RichardLitt/awesome-conferences

- readme.md
The list has been discontinued, as explained on their README.
> Remove `A-Frame VR`

- readme.md
[rosarior/awesome-django](https://github.com/rosarior/awesome-django) doesn't exist anymore.
@wsvincent would you be interested submitting your [Awesome Django list](https://github.com/wsvincent/awesome-django)?
---
Closes #1484 
Fixes #1478
> Remove rosarior/awesome-django (dead link)

- readme.md
**Awesome JAMstack:  https://github.com/automata/awesome-jamstack**
This is a curated list of resources about JAMstack, a modern web development architecture based on client-side JavaScript, reusable APIs, and prebuilt Markup. I started this list for my own while researching about JAMstack and decided to make it public. JAMstack is an ecosystem composed by many individual components and it's really hard to know about each part while they're spread at different places on Web. That's why I believe the JAMstack community needs a common `awesome-list` index.
PR reviews:
- https://github.com/sindresorhus/awesome/pull/1469#issuecomment-443503525
- https://github.com/sindresorhus/awesome/pull/1466#issuecomment-443506868
There are two other lists but they are outdated, with almost no content and …
> Add JAMstack

- readme.md
https://github.com/myshov/awesome-mobile-web-development
**There are great articles about mobile web development, there are tools for creating great mobile experience. But there is no awesome list about this topic yet.**
- Include a short description about the project/theme of the list. …
> Add Mobile Web Development

- readme.md
Where:
**https://github.com/ohenley/awesome-ada#readme**
What:
**A curated list of awesome resources related to the Ada and SPARK programming language**
Comments over other pull requests:
**https://github.com/sindresorhus/awesome/pull/1472#issuecomment-448830383**
**https://github.com/sindresorhus/awesome/pull/1457#issuecomment-448828524**
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here …
> Add Ada/SPARK

- readme.md
I don't keep this list updated, the comments in it are not sufficient, and I do not think that it is awesome. 
I want to remove this list from here to allow someone else to add their own awesome list. I'm not interested in maintaining my list anymore.
> Remove Styleguides

- readme.md
More details here:
https://github.com/guipdutra/awesome-geek-podcasts/commit/43f2ce5cb6108397674682d4ff2eaa3f6b5df884
**https://github.com/ayr-ton/awesome-geek-podcasts/**
**The list already exists. It was migrated from guipdutra to ayr-ton(my user) because of permissions for configuring the travis. I'm the core maintainer of the repository for almost a year now, so I think is good idea moving**
**I have read it multiple times.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sindresorhus/awesome/1522)
> Update Podcasts list URL

- readme.md
https://github.com/victorshinya/awesome-ibmcloud
The IBM Cloud is a cloud platform powered by the world's most popular open source projects. With integrated deployment models spanning public, dedicated, local, and hybrid clouds, the Cloud represents a new way to experience the cloud. In addition, it gives developers instant access to over 150 services including IoT and Watson APIs. Solve real-world problems and drive business value with applications, infrastructure, and services.
And assuming there are other cloud platforms such as AWS, Heroku, Digital Ocean and so on, it would be more complete to have the IBM Cloud as well. …
> Add IBM Cloud

- readme.md
[awesome-firebase](https://github.com/jthegedus/awesome-firebase)
This is the awesome-list I wanted to exist for the Firebase platform.
My two PR reviews:
* https://github.com/sindresorhus/awesome/pull/1491
* https://github.com/sindresorhus/awesome/pull/1434
I've read this so many times I doubt myself now so just going to PR this haha.
> Add Firebase

- readme.md
> Add Related section

- readme.md
**https://github.com/erictleung/awesome-nosql-guides**
**Curated list of resources and links about using NoSQL databases and things to look for when deciding to use one.**
Closes #349 
[At least two PR reviews by me](https://github.com/sindresorhus/awesome/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+reviewed-by%3Aerictleung+)
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you …
> Add NoSQL Guides

- readme.md
https://github.com/edm00se/awesome-board-games
This awesome list is an awesome list for board games. Often times we should interact with each other and enjoy some time away from the screen. Board games are a great way to interact, spend time, learn, and grow for people of all ages.
This awesome list has an additional component in that it makes use of [vuepress](https://vuepress.vuejs.org/) to build out a static version of the site on each commit to master, making for an easily searchable and non-techie friendly format for sharing for anyone. This meets the requirement in that the repo itself has non-generated markdown (per requirements below).
Per #1363, I have reviewed the following PRs:
- #1297
- #1174
- #1369
**Please read it multiple times. I spent a lot of time on these guidelines …
> Add Board Games

- readme.md
[30 seconds of code](https://github.com/30-seconds/30-seconds-of-code#readme)
**30 seconds of code** is a curated collection of JS snippets that you can understand in 30 seconds or less. A lot of work has been put into it and it provides a lot of value for JS developers.
**Note:** This is a follow-up PR for #1421. A few things have been fixed on the repository, I have reviewed 2+ PRs and I think the link is under the appropriate category.
- **You have to review at least 2 other [open pull requests] (https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when …
> Add 30 Seconds of Code

- readme.md
**Awesome CSS Learning**
https://github.com/micromata/awesome-css-learning
**It’s a list limited to the best CSS learning resources**
Mainly about CSS – the language and the modules. Not about naming conventions, architecture paradigms, frameworks, pre-processors, post-processors or other aspects of todays CSS ecosystem.
It should be included, because its a great starting point to help new frontend developers to learn CSS.
- This pull request has a …
> Add CSS Learning

- readme.md
https://github.com/seriousmac/awesome-qa/blob/master/README.md
Question Answering (QA) is a specialized area in the field of Natural Language Processing (NLP) and Information Retrieval (IR). The QA systems are concerned with providing relevant answers in response to questions proposed in natural language.  Natural language QA is recognized as a capability with great potential. Traditionally, QA has attracted many AI researchers, but most QA systems developed are toy systems or games confined to lab and a very restricted domain. More recently, Many innovations have been made with the development of artificial intelligence.
Pull requests I reviewed:
#1412 
#1174 
- **You have to review …
> Add Question Answering

- readme.md
**https://github.com/bs-community/awesome-minecraft**
**Minecraft is a famous sandbox video game and it has a wonderful eco-system like mods and other softwares.**
- I have read and understood the [instructions …
> Add Minecraft

- readme.md
- I have read and understood the [instructions for creating a …
> Update link to PICO-8 list

- readme.md
https://github.com/ScaleLeap/awesome-amazon-seller
A curated list of tools and resources for Amazon sellers.
Reviewed PRs:
- #1513
- #1523
----
- I have read and understood the [instructions for creating a …
> Add Amazon Sellers

- readme.md
https://github.com/beardicus/awesome-plotters
"A curated list of code and resources for pen plotters and other robots that draw." I'd love to see more art, design, and creative coding lists out there!
_**This passes `awesome-lint`, I've reviewed #1284 and #1524, and I have triple-checked the requirements below.**_
- ✅ **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. …
> Add Plotters

- readme.md
Add Awesome Search to #related section. #427 
Thanks.
> Add Awesome Search to the Related section

- readme.md
https://github.com/meitar/awesome-cybersecurity-blueteam#readme
This list is focused on curating a big picture overview of tools and
resources dealing with collaborative security flaw identification,
remediation, and verification. It is a relatively new list that provides
a holistic subset of several other security-related lists along with a
number of new items focused primarily around the needs of DevSecOps/Blue
Team needs in an organization. Relevant other lists, such as awesome IR,
awesome pentest, etc., are linked where relevant so as not to duplicate
work or reinvent the wheel. (Instead, I contribute to those other
lists directly when more appropriate than adding to this list.)
Thanks for the consideration.
**Please read it multiple times. I spent a lot of time on these guidelines …
> Add Cybersecurity Blue Team

- readme.md
https://github.com/bcoe/awesome-cross-platform-nodejs
Libraries and resources related to writing Node.js that works on Windows, Mac, Linux and BSD, by @bcoe.
Why this matters: according to the [2018 Node.js user survey](https://nodejs.org/en/user-survey-report/#Primary-OS-Distro), 24% of Node.js developers use Windows locally and 41% use Mac. In production 85% use Linux and 1% use BSD.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the …
> Add Cross-Platform Node.js

- readme.md
Add another list focuses on different aspect of informatics.
I placed it under bioinformatics because it is closely related.
> Add Cheminformatics

- readme.md
https://github.com/teoga/awesome-product-design
A collection of bookmarks, resources, articles for product designers.
As a product designer you go through many steps such as research, ux, ui, interactions, visuals, ux writing and so on.
This list is intended to have links and articles to guide designers on every step of the way to create their products.
**>>> I've reviewed #1536 and #1538**
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make …
> Add Product Design

- readme.md
**[https://github.com/dspinellis/awesome-msr](https://github.com/dspinellis/awesome-msr)**
**Data sets associated with empirical software engineering research that is conducted by mining software repositories and by using search-based software engineering methods**
- Include a short …
> Add Empirical Software Engineering

- readme.md
https://github.com/ironcev/awesome-roslyn
A curated list of Roslyn books, tutorials, open source projects, analyzers, code fixes, and refactorings.
Roslyn is C#/VB.NET Compiler-as-a-Service and as such it is awesome in its own :-) This list captures awesome learning materials as well as awesome open source projects built on top of Roslyn.
> Add Roslyn

- readme.md
**[Awesome React Hooks](https://github.com/glauberfc/awesome-react-hooks)**
**A list about React Hooks new feature with very good links about this subject**
PR reviews:
#1482
#1451
> Add React Hooks

- readme.md
https://github.com/adafruit/awesome-adafruitio
List containing resources for Adafruit IO, an easy-to-use internet-of-things platform designed for everyone.
Awesome-Lint Passing
> awesome-lint
> ✔ Linting
- I …
> Add Adafruit IO

- readme.md
**https://github.com/lauthieb/awesome-storybook**
**awesome-storybook** is a collection of awesome @storybooks resources like tutorials, presentations, examples and blog posts.
Many people in the community already use it and I really hope it can be added to this repository.
**Awesome-Lint Passing**
> awesome-lint
✔ Linting
**PR reviews**
- #1563 
- #1566
- #1559
**What is Storybook?**
[Storybook](https://storybook.js.org) is a user interface development environment and playground for UI components. The tool enables developers to create components independently and showcase components interactively in an isolated development environment.
Storybook runs outside of the main app so users can develop UI components in isolation without worrying about app specific dependencies and requirements._ …
> Add Storybook

- readme.md
[#928](https://github.com/sindresorhus/awesome/issues/928)
Added descriptions for Android, React Native, macOS, Swift, Python, C/C++, Java, PHP, CSS, and Kubernetes.
> Add descriptions

- readme.md
Adding a list for anyone to learn more about product management.
**https://github.com/dend/awesome-product-management**
**The list presents resources for anyone to start with product management. It contains pointers to good articles, tools, books and podcasts that can help accelerate one's PM training.**
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected …
> Add Project Management

- readme.md
https://github.com/tindzk/awesome-scala-native
[Scala Native](http://www.scala-native.org/) is an optimising ahead-of-time compiler for the [Scala programming language](https://www.scala-lang.org/).
- Include a short description about the project/theme of the list. **It should not …
> Add Scala Native

- readme.md
https://github.com/leomaurodesenv/game-datasets
This repository serves as a guide for anyone who wants to work with Data Mining or Artificial Intelligence applied in digital games, with several tools and datasets.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for …
> Add Game Datasets

- readme.md
https://github.com/stackshareio/awesome-stacks
The list took off pretty much the next day. We just recently hit the 1 month mark and we are close to 1,800 stars. A few developers emailed us saying "thank you" which was amazing. I mention that because people are getting a lot of value out of it which is awesome.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. …
> Add Stacks

- readme.md
Updates a few awesome lists that have changed URL.
> Update URLs from GitHub username changes

- readme.md
https://github.com/AdrienTorris/awesome-blazor
Blazor is a new product from Microsoft and the 'Awesome Blazor' repository is considered as the official community website, see the official Blazor's website: https://dotnet.microsoft.com/apps/aspnet/web-apps/client (section 'Active community').
[Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/client) is a feature of ASP.NET, the popular web development framework that extends the .NET developer platform with tools and libraries for building web apps. It lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries.
Appropriate category: Front-End …
> Add Blazor

- readme.md
**https://github.com/eselkin/awesome-computational-neuroscience**
**The list identifies higher education researchers in computational neuroscience at a number of institutions around the world. It aims to capture all institutions that have a program offering in computational neuroscience, systems neuroscience, and theoretical neuroscience**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. …
> Add Computational Neuroscience

- readme.md
**[https://github.com/fkie-cad/awesome-embedded-and-iot-security#readme](https://github.com/fkie-cad/awesome-embedded-and-iot-security#readme)**
**Security analysis of embedded and IoT differs from normal security stuff. There are a lot of awesome tools and resources. However there was no curated list of the *good* stuff. Here it is!**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This …
> Add Embedded and IoT Security

- readme.md
**https://github.com/CompSciLauren/awesome-git-hooks**
**This list is about git hooks, scripts that can be customized to automate a wide variety of tasks during git workflows.**
Yes
Yes
Understood
PR: https://github.com/sindresorhus/awesome/pull/1582
PR: https://github.com/sindresorhus/awesome/pull/1585
- You have read and understood the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
Yes
- This pull request has …
> Add Git Hooks

- readme.md
Added description for Back-End Development.
Related to #928.
> Add description to some entries

- readme.md
https://github.com/cytodata/awesome-cytodata
This page represents a curated list of software, datasets, landmark publications, and image-based profiling methods. The goal of this list is to provide researchers, both new and established, a place to discover and document awesome Cytodata resources.
Cytodata refers to a community of researchers and resources involved in the image-based profiling of biological phenotypes. These biological phenotypes are typically induced by genetic or chemical perturbations and often represent disease states. Image-based profiling is used to inspect these phenotypes to uncover biological insight including discovering the impact of genetic alterations and determining the mechanism of action of compounds.
**Please read it multiple times. I spent a lot of time …
> Add Cytodata

- readme.md
**https://github.com/nglgzz/awesome-clean-tech**
**List of awesome clean tech companies and research on climate change.**
PRs Reviewed:
https://github.com/sindresorhus/awesome/pull/1611
https://github.com/sindresorhus/awesome/pull/1610
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you …
> Add Clean Tech

- readme.md
**https://github.com/cenoura/awesome-ads**
**A curated list of advertising and programmatic media related content, resources to learn about it and libraries to implement it on your website.**
PRs reviewed:
https://github.com/sindresorhus/awesome/pull/1596#issuecomment-530011763
https://github.com/sindresorhus/awesome/pull/1612#issuecomment-530010320
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when …
> Add Advertising

- readme.md
https://github.com/ravirupareliya/awesome-aog
A curated list of awesome AoG(Action on Google) libraries, blogs, open-source project, videos.
PRs reviewed:
[#1613 (comment)](https://github.com/sindresorhus/awesome/pull/1613#issuecomment-530035621)
[#1606 (comment)](https://github.com/sindresorhus/awesome/pull/1606#issuecomment-529618538)
[#1612 (comment)](https://github.com/sindresorhus/awesome/pull/1612#issuecomment-529615844)
Try to prioritize unreviewed PRs, but you …
> Add Actions on Google

- readme.md
**[https://github.com/krzjoa/awesome-python-data-science](https://github.com/krzjoa/awesome-python-data-science)**
**Comprehensive list of Python libraries for Data Science: Machine Learning, Data Analysis, Visualization, Probabilistic Modelling etc.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here …
> Add Python Data Science

- readme.md
**https://github.com/csabapalfi/awesome-web-performance-metrics**
**It's list of web performance metrics 400+ stars and @pajaydev opened an issue that I should add it here (https://github.com/csabapalfi/awesome-web-performance-metrics/issues/1)**
PRs reviewed:
https://github.com/sindresorhus/awesome/pull/1611#discussion_r319776923
https://github.com/sindresorhus/awesome/pull/1610#discussion_r319777058
Try to prioritize unreviewed PRs, but you can also add more …
> Add Web Performance Metrics

- readme.md
https://github.com/playcanvas/awesome-playcanvas#readme
A curated list of tools, tutorials, examples, and much more, for the awesome game development engine PlayCanvas.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed:
https://github.com/sindresorhus/awesome/pull/1644 …
> Add PlayCanvas

- readme.md
https://github.com/aniftyco/awesome-tailwindcss
A curated list of awesome things related to the Tailwind CSS framework.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. …
> Add Tailwind CSS

- readme.md
https://github.com/henrikwirth/awesome-wordpress-gatsby
A curated list of resources about WordPress as a headless CMS with Gatsby
PRs reviewed: 
#1622 
#1623 
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look …
> Add WordPress-Gatsby

- readme.md
https://github.com/ildoc/awesome-italy-events#readme
A curated list of Tech related events in Italy
**PR Reviewed:** https://github.com/sindresorhus/awesome/pull/1657#issuecomment-554267442, https://github.com/sindresorhus/awesome/pull/1657#pullrequestreview-317479724
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. …
> Add Italy Events

- readme.md
https://github.com/typeddjango/awesome-python-typing
Collection of awesome Python types, stubs, plugins, and tools to work with them.
Links: [#1636](https://github.com/sindresorhus/awesome/pull/1636) and [#1638](https://github.com/sindresorhus/awesome/pull/1638)
- ✅ `Add Python Typing`
- ✅ `- [Typing](…) - Types and tools to work with them for Python.`
- ✅ `Collection of awesome Python types, stubs, plugins, and tools to work with them.`
- ✅ `awesome-python-typing`
- ✅ `# Awesome Python Typing`
**Go to the top and read it again.**
> Add Python Typing

- readme.md
**https://github.com/maehr/awesome-digital-history#awesome-digital-history-**
**In the historical sciences and other humanities disciplines, digital tools have become an integral part of everyday academic life. Lots of scholars struggle to find adequate tools and to exchange such knowledge. This is why I brought together the best tools, source collections and platforms for digital history and related disciplines.**
Try to prioritize unreviewed PRs, but you can also …
> Add Digital History

- readme.md
**https://github.com/PandaFoss/Awesome-Arch/blob/master/README.md**
**Arch Linux is an independently developed, x86-64 general purpose GNU/Linux distribution versatile enough to suit any role. This awesome list aims to collect all those projects based on Arch Linux and its philosophy.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome …
> Add Arch-based Projects

- readme.md
**https://github.com/wardley-maps-community/awesome-wardley-maps**
Useful Wardley mapping resources. The creator of Wardley maps, Simon Wardley, now recognizes and promotes this list as the Awesome list for Wardley mapping:
https://twitter.com/swardley/status/1170029501516079105
PRs reviewed: #1627, #1628
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help …
> Add Wardley Maps

- readme.md
https://github.com/gruhn/awesome-naming
In reference to the famous quote by Phil Karlton:
> There are only two hard things in Computer Science: cache invalidation and naming things.
this is a list of examples where people actually came up with clever, creative and funny names for stuff from any field of computer science.
I know `awesome-lint` fails with:
```sh
✖ Linting
README.md:1:1
✖  1:1  Missing License section  remark-lint:awesome-license
1 error
```
I tried to comply with the [new requirements, not implemented yet in awesome-lint](https://github.com/sindresorhus/awesome-lint/issues/93)
I reviewed. #1660, #1653
- **Don't waste my time.** Do a good job, adhere to all the …
> Add Naming

- readme.md
**https://github.com/seed-rs/awesome-seed-rs**
**A curated list of awesome things related to Seed - an open-source Rust framework for creating  web apps running in WebAssembly. This list should help frontend developers with learning Seed and Seed/Elm architectural patterns and with creating fast and reliable WASM apps.**
PRs reviewed:
https://github.com/sindresorhus/awesome/pull/1666#pullrequestreview-326721167
https://github.com/sindresorhus/awesome/pull/1669#pullrequestreview-326714591 …
> Add Seed RS

- readme.md
https://github.com/sdras/awesome-actions
Actions automate workflows and allow you to build, test, and deploy your code from GitHub. This list showcases actions and tutorials from the community.
🖖 I have read through the requirements multiple times. I believe it satisfies all of the requirements.
> Add GitHub Actions

- readme.md
**https://github.com/sduff/awesome-splunk**
**Splunk is a big-data solution with many additional applications. This awesome list aims to capture the best and current resources**
Rather than pollute the Miscellaneous further, I have included awesome-es and awesome-itsi, both Splunk applications, as sub-list items under the Splunk heading.
Reviewed #1623 and #1622 
- You have read and understood the [instructions for creating a …
> Add Splunk

- readme.md
https://github.com/tokenmill/awesome-nlg
List of tools, data-sets and projects in the area of Natural Language Generation.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for …
> Add Natural Language Generation

- readme.md
Hi! First of all thank you very much for your project, I found a lot of useful staff in a variety awesome lists.
https://github.com/sergey-pimenov/awesome-web-animation
A list of awesome web animation libraries, books, apps etc.
Over the years, I've collected a lot of useful tools for web animation. In the current version of this list, I thoroughly cleaned up some legacy libraries and tried to keep only useful stuff.
In addition, I created a [web page](https://awesome-web-animation.netlify.com/) version that takes some useful data (with Github API) about libraries - bundle size, last update, issues counter. I also use Google Books API to provide some useful data about books - price, page counter, description etc.
Reviewed PR's: https://github.com/sindresorhus/awesome/pull/1666 …
> Add Web Animation

- readme.md
Adding StumbleUponAwesome - this is a Chrome extension I made which lets you discover the Awesome dataset, like StumbleUpon was back in the day. 
Not sure if it should link to Github repo or straight to the Chrome Web Store to download?
> Add StumbleUponAwesome

- readme.md
**[https://github.com/umutphp/awesome-cli](https://github.com/umutphp/awesome-cli)**
It is not a list :). It is a simple CLI tool to dive into Awesome lists from command line.
Reviewed PRs:
#1720 
#1703 
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a …
> Add Awesome CLI

- readme.md
**https://github.com/iipc/awesome-web-archiving**
**This list is about web archiving, a discipline that preserves the Web as a historical record for future generations. This discipline has been around for over two decades now. The community includes various libraries, memory organizations, and national organizations.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is …
> Add Web Archiving

- readme.md
https://github.com/radek-sprta/awesome-game-remakes/
Actively maintained open-source game remakes. Projects that allow you to play classic games on modern systems, often fixing bugs, adding new features or even open-source assets.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. …
> Add Game Remakes

- readme.md
not a new list
request to move  awesome-plotters to hardware section
> Move `Plotters` list to Hardware section

- readme.md
not a new list, just url changes reported by [awesome_bot](https://github.com/dkhamsing/awesome_bot/)
Two concerns:
- ⚠️[analysis-tools-dev/static-analysis](https://github.com/analysis-tools-dev/static-analysis) no longer has the `awesome-` prefix (but still has awesome branding in its readme)
- 🚨[MFatihMAR/Game-Networking-Resources](https://github.com/MFatihMAR/Game-Networking-Resources) no longer has awesome branding at all (although it is still a high quality list)
> Update renamed users and repos

- readme.md
https://github.com/mcauser/awesome-micropython/
Libraries, frameworks, tools and resources for MicroPython running on microcontrollers.
By submitting this pull request I confirm I've read and complied with the below requirements 🖖
`awesome-lint` passed without error, except for false positives `no-dead-urls`.
I hit each failing url independently and confirm they are not 404ing.
PRs reviewed: #1775, #1760, #1720, #1699
> Add MicroPython

- readme.md
Source: https://github.com/topics/julia
> Add the description for Julia language

- readme.md
**https://github.com/rtckit/awesome-rtc**
**Curated list of Real Time Communications (RTC) resources, ranging from old school Voice over IP to the latest WebRTC protocol collection. The list is relevant to various groups of users, systems integrators, operations and developers, beginners or practitioners alike.**
Reviewed PRs: #1643, #1655
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. …
> Add Real Time Communications

- readme.md
**https://github.com/mxschmitt/awesome-playwright**
**It's about the [Playwright](https://github.com/microsoft/playwright) project which gained in the past few month a lot popularity. With it you can control WebKit, Firefox and Chromium with a single Node.js API. It's made by the same team as the Puppeteer project which has only supported Chromium based browsers. With that and the cross-browser support, it provides a solid foundation to create e.g. e2e tests or other smaller tools which rely on multiple browsers to be controlled via Node.js.**
Reviewed PRs: #1753 #1747
- **You have to review at …
> Add Playwright

- readme.md
https://github.com/aaronhma/awesome-tensorflow-js
This repository contains a curated list of dedicated resources to help you become a ninja at TensorFlow.js.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look …
> Add TensorFlow.js

- readme.md
Reopened from https://github.com/sindresorhus/awesome/pull/1789 (PR to `master`)
https://github.com/componently-com/awesome-building-blocks-for-web-apps
Standalone features to be integrated into web applications. It should be included because it's awesome not having to code the same functionality over and over again.
> Add Building Blocks for Web Apps

- readme.md
By @writing-resources @ashwinvis and @maehr 
Discussion can be found here https://github.com/sindresorhus/awesome/pull/1700
https://github.com/writing-resources/awesome-scientific-writing
Open source tools for painless academic writing.
This should be included, because academic writing is a hassle.
PRs:
- https://github.com/sindresorhus/awesome/pull/1735
- https://github.com/sindresorhus/awesome/pull/1635
- https://github.com/sindresorhus/awesome/pull/1644
Try to …
> Add Scientific Writing

- readme.md
**https://github.com/schlessera/awesome-wp-cli#readme**
**Awesome list for WP-CLI, the command-line interface for WordPress. WP-CLI is a critical piece of infrastructure for the WordPress ecosystem and a huge productivity boost for development and site management. It needs an awesome list because very few people make use of a larger portion of its potential, as they don't know about all the awesome third-party extension packages and helpful guides that would allow them to shift into next gear.**
Note: `awesome-lint` is enforced on the list via a GitHub Action.
Reviewed PRs:
- https://github.com/sindresorhus/awesome/pull/1757
- https://github.com/sindresorhus/awesome/pull/1769
Related closed PR before the main branch change:
- https://github.com/sindresorhus/awesome/pull/1770
**Please read …
> Add WP-CLI

- readme.md
This [list](https://github.com/SE-ML/awesome-seml/blob/master/readme.md ) includes articles recommending or describing software engineering best practices for building machine learning applications.
More informations can be found in the [old pull request](https://github.com/sindresorhus/awesome/pull/1722) which was automatically closed.
It is more than 30 days old and has over 420 stars.
We reviewed 2 PRs: [1](https://github.com/sindresorhus/awesome/pull/1704) and [2](https://github.com/sindresorhus/awesome/pull/1682).
Some linting issues were ignored because the emojis used to flag publications as academic or must-read (see list) are not considered a description.
**https://github.com/SE-ML/awesome-seml/blob/master/readme.md**
**Software engineering is complementary to any machine …
> Add Software Engineering for Machine Learning

- readme.md
Duplicate of #1775.
**[[https://github.com/stingalleman/awesome-audiovisual](https://github.com/stingalleman/awesome-audiovisual)]**
**[This list is a combination of software, libraries and resources for audio, video and lighting professionals and hobbyists.]**
> I reviewed #1769 & #1758 
Duplicate of #1775.
> Add Audiovisual

- readme.md
**https://github.com/TaptuIT/awesome-devsecops**
This list is a collection of resources and tooling related to DevSecOps. DevSecOps is an extension of DevOps - a methodology and philosophy for software development - that aims to incorporate security expertise and testing into the development lifecycle, with the goal of creating more secure software.
This list of resources can help software development teams learn about and adopt DevSecOps practices and tooling, resulting in more secure software for everybody.
Reviewed PRs: #1756 #1758
By submitting this pull request I confirm I've read and complied with the below requirements 🖖
> Add DevSecOps

- readme.md
Hey @sindresorhus 
just removing a dead link to a deleted repo (and profile).
Cheers,
Peter
> Remove Assembler

- readme.md
1. PR Reviewed: [__1__](https://github.com/sindresorhus/awesome/pull/1812#pullrequestreview-438679163), [__2__](https://github.com/sindresorhus/awesome/pull/1808#pullrequestreview-438734848), [__3__](https://github.com/sindresorhus/awesome/pull/1811#pullrequestreview-438736118), [__4__](https://github.com/sindresorhus/awesome/pull/1804#pullrequestreview-438821530)
2. The list over 30-days old, has over 150 stars
3. I [__explained here__](https://github.com/mhxion/awesome-discord-communities/blob/main/FAQ.md#why-does-not-this-list-follow-convential-awesome-list-framework) why I'd used `Notable Channels` and [badges](https://github.com/mhxion/awesome-discord-communities/blob/main/badges.md) instead a description for each entry.
4. Only …
> Add Discord Communities

- pull_request_template.md
Proposed by @sindresorhus at https://github.com/sindresorhus/awesome-lint/pull/118#issuecomment-686778864
> Sync PR template with ToC rules about silenced sections

- readme.md
**https://github.com/RayBB/awesome-social-enterprise**
**This is a list of literature, tools, and communities about social enterprise. Right no social enterprise, is a small but growing field that is focused on building organizations that are primarily focused on social impact and is at least partially self-funded.**
- Gave feedback for 2 PRs [here](https://github.com/sindresorhus/awesome/pulls?q=commenter%3Araybb).
- ✅ `- [iOS](…) - Mobile operating …
> Add Social Enterprise

- readme.md
Original PR [#1837](https://github.com/sindresorhus/awesome/pull/1837) was orphaned by mistake. This PR replaces it.
[https://github.com/iamericfletcher/awesome-r-learning-resources#readme](https://github.com/iamericfletcher/awesome-r-learning-resources#readme)
This list is a collection of resources related to R, a programming language and environment for statistical computing and graphics. It is meant to help users from all skill levels and backgrounds deepen their understanding of R, resulting in a more knowledgable programming population that benefits everybody involved.
Reviewed PRs: #1857 #1848
- **Don't waste my time.** Do a good job, adhere to all the guidelines, and be …
> Add R Learning

- readme.md
**https://github.com/mourarthur/awesome-credit-modeling**
The list consolidates several resources on the subject of credit risk modeling and credit scoring. The financial services industry has seen deep changes in the past decade due to the increase in data variety and availability when it comes to determining a consumer's creditworthiness.
- Reviewed PRs: #1784 , #1797 , #1798 , #1803 .
- PR Name: **Add Credit Modeling**
- Entry: **Methods for classifying credit applicants into risk classes.**
> Add Credit Modeling

- readme.md
**https://github.com/tobiasvl/awesome-chip-8**
**Created in 1977, CHIP-8 is the original fantasy console. It has been implemented on countless computers the last 40 years, and there are over 4000 CHIP-8 repositories on GitHub, mostly emulators. New software is also being made for CHIP-8, in an annual game jam.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to …
> Add CHIP-8

- readme.md
**[https://github.com/protontypes/awesome-sustainable-technology](https://github.com/protontypes/awesome-sustainable-technology)**
**[Open source projects sustaining stable climate, energy supply and vital natural resources. So far there is no comparable list in this area. Sustainable technologies concern us all and ensure that knowledge and technology in this area will remain our superiority in the long term.  ]**
> Check
Try to prioritize unreviewed PRs, but you can …
> Add Sustainable Technology

- readme.md
https://github.com/KeyboardInterrupt/awesome-ansible
Ansible is a Configuration Management System and People have built Awesome Tools and Automation around and with it.
The goal of the list is to create a curated List of great resources around Ansible and it's Ecosystem.
- **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).** --> #1838 & #1794 & #1816 
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the …
> Add Ansible

- pull_request_template.md
- readme.md
https://github.com/blade-ui-kit/awesome-tall-stack
I'd like to submit the Awesome TALL Stack list which features a resources on a full stack solution using libraries built by the Laravel community. On here, developers can find resources specific to the TALL stack (and not the individual libraries) to help them learn, code and built their next app.
I hope I did all the steps correctly! 🤞 🙂
> Add TALL Stack

- readme.md
https://github.com/substrate-developer-hub/awesome-substrate
A curated lists of awesome projects and resources related to the Substrate blockchain development framework. 
:heavy_check_mark:  **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
:heavy_check_mark:  **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
> https://github.com/sindresorhus/awesome/pull/1867
> https://github.com/sindresorhus/awesome/pull/1866
> https://github.com/sindresorhus/awesome/pull/1859
:heavy_check_mark:  You have read and understood the [instructions for creating a list](create-list.md).
:heavy_check_mark:  This pull request has a title in the format `Add Name of List`.
:heavy_check_mark:  Your …
> Add Substrate

- pull_request_template.md
- readme.md
**[https://github.com/margaretmz/awesome-tensorflow-lite](https://github.com/margaretmz/awesome-tensorflow-lite)**
**About**
This repo contains a list of TensorFlow Lite models with sample apps, tutorials, and resources to showcase what the community has built and help you learn on-device ML.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome …
> Add TensorFlow Lite

- readme.md
**https://github.com/j0hnm4r5/awesome-creative-technology**
**Awesome Creative Technology is a list of businesses & groups that specialize in Creative Technology, which is a field that combines computing, design, art, and user experience. It is a reference for job seekers and inspiration.**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement …
> Add Creative Technology

- readme.md
**https://github.com/JoseDeFreitas/awesome-youtubers**
**"Watch videos and playlists from YouTubers that teach you about technology." In this list, you can find YouTube channels that teach several technology topics, such as programming, design, security, and a lot more. I created this list because I find very often video tutorials much better than documentation. You can learn a lot with the playlists and videos these YouTubes have created.**
2 pull requests I've reviewed: #1859 and #1866.
_The only issue [awesome-lint](https://github.com/sindresorhus/awesome-lint) is throwing is "Missing main list heading". The title is correct, but not using markdown format (`# Title`) but instead HTML tags (`<h1>Title</h1>`). This is because I want the header to be centered, and I couldn't do it without …
> Add YouTubers

- readme.md
https://github.com/wernerkrauss/awesome-silverstripe-cms
Silverstripe CMS a rapid development MVC framework that serves as a classic fully fledged CMS or as a headless CMS, which can be queried either via GraphQL or a custom API.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. …
> Add Silverstripe CMS

- readme.md
**[https://github.com/protontypes/awesome-robotic-tooling]**
**[Robotic resources and tools for professional development in C++ or Python with a touch of ROS, autonomous driving and aerospace. This list was created mainly at my work at the department of autonomous logistics at DHL. Our goal was to create a complete development environment for robotics based on open tooling. All the tools we used and other interesting resources we found are in this list. It is the largest list of free and open resources in robotics. Many members of the open-source robotic community participated on this list. As the field of robotics today also has a lot of overlaps with the automotive and aerospace sector, there are also many projects in this area.  ]**
**Please read it multiple times. I spent a lot of …
> Add Robotic Tooling

- readme.md
https://github.com/keller-mark/awesome-biological-visualizations
Web-based biology-related visualization tools are often scattered across the internet and difficult to discover. They may be found on GitHub, Twitter, or linked from scientific papers. These tools can be very useful to scientists looking to visualize biological data in the context of diseased or healthy humans or model organisms.
Try to prioritize unreviewed PRs, but you can also add more comments to …
> Add Biological Visualizations

- readme.md
https://github.com/sdassow/awesome-veganism
This list contains entries to make veganism easy and accessible to everyone who is interested. There are many rather random, unmoderated, or unmaintained lists created by individuals or companies, with sometimes questionable quality. This list is an attempt to create a community driven approach to guarantee no-nonsense content, 100% aligned with the life-style, in order to minimise the effort needed for an awesome experience.
- The list is around for 2+ months.
- Checked with awesome-lint.
- Reviewed PRs: https://github.com/sindresorhus/awesome/pull/1876#issuecomment-706613089, https://github.com/sindresorhus/awesome/pull/1879#issuecomment-706614447, https://github.com/sindresorhus/awesome/pull/1884, and merged PRs to see what success looks …
> Add Veganism

- readme.md
[https://github.com/klaufel/awesome-design-systems](https://github.com/klaufel/awesome-design-systems)
About design system definition, is an ever evolving collection of reusable components, guided by rules that ensure consistency and speed, by being the single source of truth for any product development, this `awesome` list, focused on frontend development of design systems. A curated list of bookmarks, articles  and more resources of design systems focused on developers.
3 pull requests I've reviewed: #1865, #1863 and #1859
https://github.com/sindresorhus/awesome/pull/1865#issuecomment-703268307
https://github.com/sindresorhus/awesome/pull/1859#issuecomment-703269398
https://github.com/sindresorhus/awesome/pull/1863#issuecomment-703268737
**[Explain what …
> Add Design Systems

- readme.md
**https://github.com/michelpereira/awesome-games-of-coding/**
The purpose of this list is to practice a new programming language by coding a game, solving puzzles or teaching robots to attack and defend itself like in Vindinium.
- The list is around for 4+ years.
- Have been discussed on Hackernews: https://news.ycombinator.com/item?id=13566247
- Reviewed PRs: #1886
- Comments made: #1912 (comment)
- Suggestion made to other lists: #1907 (comment)
Try to prioritize …
> Add Games of Coding

- readme.md
**https://github.com/aureooms/awesome-qr-code**
**This is a curated list of QR code libraries, software and resources.** I created it because I could not find any other such list. I have used some of the listed items and even created some.
I have reviewed [the following open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+reviewed-by%3Aaureooms): #1816, #1851, #1868, #1869.
> Add QR Code

- readme.md
**https://github.com/agamm/awesome-developer-first**
**There is a growing trend of developer-first products, products that target developers specifically. There is currently no place that aggregates all of them. This can help developers to find relevant products and tools. This is highly related to the trend of outsourcing tasks (JAMStack mantra) like auth0/firebase and more replace a lot of the work required for authentication which was coded again and again. Now there are more products in several areas that solve the same developer pain points. This is why I decided to help myself and others find these products.**
- **Don't waste my time.** Do a good job, adhere to all the …
> Add Developer-First Products

- readme.md
[Testing] Adding Software Testing & QA Roadmap repository link
https://github.com/fityanos/awesome-quality-assurance-roadmap
This repository includes:
- Rich roadmap highlights software testing and software QA.
- Test Plan sample pdf for downloading and private usage.
- Translations to support community.
> Add Quality Assurance Roadmap

- readme.md
**https://github.com/sindresorhus/awesome**
**Discussed with Sindre over email about adding this awesome list visualizer ( http://awesome.digitalbunker.dev/ ) to the Resources section**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into …
> Add Awesome Viewer to Related section

- readme.md
**https://github.com/Anant/awesome-cassandra**
**Apache Cassandra is a free and open-source, distributed, wide column store, NoSQL database management system designed to handle large amounts of data across many commodity servers, providing high availability with no single point of failure.**
**Reviews**
- [#1950](https://github.com/sindresorhus/awesome/pull/1950#issuecomment-824898027)
- [#1964](https://github.com/sindresorhus/awesome/pull/1964#issuecomment-824895450) …
> Add Cassandra

- readme.md
Remove Awesome Chalice, since @sindresorhus only cares about showing ads next to our content with NO ATTRIBUTION
> Remove Chalice

- readme.md
https://github.com/innocenzi/awesome-inertiajs
This list is related to [Inertia.js](https://inertiajs.com), a protocol for making single-page applications without having to design and write an API. Inertia.js requires a back-end and a front-end adapter, but I added it to the "front-end development" category because I think it's what fits the most, given the fact that there is no "web development" category, and that people use Inertia.js in order to make SPAs.
---
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR …
> Add Inertia.js

- readme.md
https://github.com/mdbootstrap/awesome-mdbootstrap
MDB is a powerful UI Kit & Tools that includes a massive library of components that make it a breeze to design websites, web apps, and mobile applications.  It's mainly made to save designers valuable time while building modern-looking websites. It would be great if everyone could get to know MDBootstrap and compare its awesome projects with other tools: :D
I reviewed:
- https://github.com/sindresorhus/awesome/pull/1973
- https://github.com/sindresorhus/awesome/pull/1938 …
> Add MDBootstrap

- readme.md
**https://github.com/mostafatouny/awesome-theoretical-computer-science/**
**Theoretical computer science curated list of valuable resources. It is the interplay of mathematics and computer science, distinguished by its mathematical rigor and technique. Theoretical computer science is not widely popular. So it is not easy to find resources or a community for it. That is the role of this awesome list**
Try to prioritize unreviewed PRs, but you can also add more comments …
> Add Theoretical Computer Science

- readme.md
**https://github.com/kdeldycke/awesome-billing**
**Why is this list awesome?**
Any company needs at one point to get money from customers. That's when things gets messy for us developers, as we try to reconcile the complexity of the business with our software stack.
This awesome list helps software engineers bootstrap billing & payments systems and make sense of invoicing, pricing, accounting, marketplace, fraud and business intelligence.
✅ I read this PR template multiple times. Better yet: I contributed to refining it: https://github.com/sindresorhus/awesome/commit/488c1051a3089e386ed223a5b45ab8ff8c53397c
Sort of. I'm involved in the community by other means:
❗ I already contributed …
> Add Billing

- readme.md
https://github.com/lodthe/awesome-internships
A lot of students look for summer internships. This repo contains useful information for them, i. e. companies who are hiring interns, guides on how to create a cv, behavioral interview advice.
I reviewed: 
- #1959
- #1961
- #1966 …
> Add Internships

- readme.md
> Add AppImage

- readme.md
https://github.com/rockerBOO/awesome-neovim
This list lists plugins for the neovim text editor.
> Add Neovim

- readme.md
https://github.com/aliesbelik/awesome-gatling
This list contains resources about the popular open-source, developer-centric performance testing framework Gatling.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. …
> Add Gatling

- pull_request_template.md
- readme.md
**https://github.com/Strift/awesome-esports**
**This is a list of programming libraries, softwares, and educational or research material related to esports. It is intended to help companies, developers, and other actors in the esports field.**
I helped reviewing 2 PRs. My comments can be found here:
- https://github.com/sindresorhus/awesome/pull/2133#issuecomment-1002670649
- https://github.com/sindresorhus/awesome/pull/2035#issuecomment-1002680536
After reading the rules, I acknowledge that this awesome list is missing logo.
PS: I _think_ Gaming is the correct category for Esports, but I'm totally open to discussion.
Thank you for your time.
Cheers,
- **Don't waste my time.** Do a …
> Add Esports

- readme.md
https://github.com/zenitysec/awesome-low-code
This is a list of awesome low-code application development platforms, resources, and tools to help citizen and professional developers dive into the low-code world.
Low-code platforms place more power in the hands of business professionals by letting them build application with minimal to no coding skills requires, mostly through a drag and drop interface. This empowers the business to address their own issues rather than ask for IT's help. It also helps proffesional developers accelarate time-to-market and reduce their maintenance costs. The low-code ecosystem is very large, and this list tries to help people navigate it.
The list helps business users and developers answer the following questions (and many more):
- Which low-code platforms …
> Add Low Code

- readme.md
**Fixing some minor problems:**
- making url `https://` from `http://`
- some github links got changed and they redirect to new ones. 
maybe because, maintainer of that list changed the username 
or transferred it to someone else. 
(please see the comments in every commit to find more info about it)
I'm not sure if i am complying with those rule because i'm not trying to add any new list.
not sure if those kind of fixing pull request is allowed or not in the first place.
I have read the all the rules and tried my best to follow those.
I did similar thing in https://github.com/troxler/awesome-css-frameworks/pull/66 ,
and planing to do it to all other lists too.
If you have any recommendation or suggestion please let me know.
every pull request looks like over reviewed. can't find anything …
> Update redirected links

- readme.md
**this is just a fix for issue #2179**
Fixes #2179
My default branch is `main` but it being used for another pull request, so i'm using this one for now.
Please check #2179, for more information where @web-padawan (maintainer of that repo) asked to update following information.
--- …
> Update info about `lit`

- readme.md
this pull request is for removing dead list **awesome-rubymotion**
more info in https://github.com/sindresorhus/awesome/issues/2187.
Fixes https://github.com/sindresorhus/awesome/issues/2187.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort …
> Remove list `RubyMotion`

- readme.md
looks like this repository has been deleted.
> Remove contexture, repository no longer exists

- readme.md
The repository for the Ansible list has been transferred to the ansible-community org,
As this PR does not add a List, but instead just updates an url, to avoid unnecessary redirection, I cannot 100% adhere to the Guidelines. But I will try to go trough them thoroughly, and for what it's worth, I checked that the List still adheres to the Guidelines!
I Reviewed the following PR's:
- https://github.com/sindresorhus/awesome/pull/2217
- https://github.com/sindresorhus/awesome/pull/2215
- **You …
> Update link to Ansible

- pull_request_template.md
To prevent draft PRs and reduce list-redundancy.
Reference the issue when mentioning "No draft PRs".
> add reference to #2242 in pull_request_template.md

- readme.md
https://github.com/directus-community/awesome-directus
List with interesting links related to [Directus]([https://github.com/directus/directus) (application which provides a real-time API and App dashboard for managing SQL database content) which helps users to find and share resources like:
* Tools and libraries to integrate Directus into their project
* Extensions to full-fill their use-cases
Try to prioritize unreviewed PRs, but you can also add more comments to …
> Add Directus

- readme.md
[Conversational AI](https://github.com/jyguyomarch/awesome-conversational-ai)
This list provides resources on Conversational AI to help anyone start building chatbots and digital assistants. It focuses on the technical part of the topic (NLU, clients, platforms) so I think it fits best in Computer science, but it will also cover topics such as Conversational Ux.
Reviewed the following two PRs:
- #2067 
- #2153 
Try to prioritize unreviewed PRs, but you can also add …
> Add Conversational AI

- readme.md
**https://github.com/Karneades/awesome-malware-persistence**
**A curated list of awesome malware persistence tools and resources.**
**Malware persistence consists of techniques that adversaries use to keep access to systems across restarts, changed credentials, and other interruptions that could cut off their access.**
The main repository which was started 2 years ago has more than 90 stars and is a reference repository regarding this specific awesome malware topic. The **awesome malware persistence list exists since more then 2 years but was integrated the main project about malware persistence until now**. (https://github.com/Karneades/malware-persistence)
The only lint error besides the age is now a duplicate URL because I point to one specific location in a repo in addition to the …
> Add Malware Persistence

- readme.md
[Esri/awesome-arcgis-developer](https://github.com/Esri/awesome-arcgis-developer)
It is a curated list of resources to help developers using [ArcGIS](https://developers.arcgis.com/) to build mapping and location analysis solutions. I think it should be included because there is no ArcGIS/Esri awesome list, and also because [Esri](https://en.wikipedia.org/wiki/Esri)'s technology (ArcGIS) [is a well-known brand](https://trends.google.com/trends/explore?date=all&q=arcgis,Mapbox,leaflet,openstreetmap) used by a huge number of developers. 
**For reference, you can see Esri/ArcGIS market position in g2.com:**
Inside the [GIS Software](https://www.g2.com/categories/gis#grid) category (compared to Google Maps API, Mapbox, Bing, OpenStreetMap, AzureMaps, ...). …
> ArcGIS Developer

- readme.md
https://github.com/osmlab/awesome-openstreetmap
This list offers a curated selection of projects interacting with [OpenStreetMap](https://www.openstreetmap.org), the open and free mapping project. With this list we aim to provide a starting point for people wanting to get into either mapping for OpenStreetMap or using the map-data for projects.
Being listed in the index of awesome-lists will help guide interested readers towards our list and make it easier for them to find what they are looking for! 🙂  …
> Add OpenStreetMap

- readme.md
**https://github.com/taosdata/awesome-tdengine**
**It's about a time-series database named TDengine**
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting …
> Add TDengine

- readme.md
https://github.com/inoue0426/awesome-computational-biology
Computational Biology is a rapidly growing field in Computer Science in recent years. In particular, it is closely related to graph theory and machine learning, but the various information on preprocessing, data sets, and methods are scattered and not coherent. For this reason, we have created this repository. In addition, since there is no one related to Computational Biology yet, we think that it is worth being included in Awsome. I hope that this repository will contribute to other research, and I also hope that it will be made available on Awsome so that more people will be able to view it.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This …
> Add Computational Biology

- readme.md
React is a library not a framework :)!
https://digitalya.co/blog/is-react-a-framework-or-library/
> React - Framework -> Library

- readme.md
https://github.com/YuzheSHI/awesome-agi-cocosci/#readme
I add AGI & CoCoSci to Awesome to fill-in its absence of academic resources on artificial general intelligence and computational cognitive sciences. 
- AGI & CoCoSci provides users with following resources:
- Classic and cutting-edge research papers and books categorized in diverse intelligent phenomena, with direct links and links to *Google Scholar All Versions*, some of which also include links to codes and project websites;
- Established institutes and researchers on related topics;
- Eminent scientists and thinkers on related topics with their historical representative books;
- BibTex templates for composing papers with latex on related topics.
Artificial General Intelligence an emerging inter-discipline field that combines …
> Add AGI & CoCoSci

- readme.md
**https://github.com/atkirtland/awesome-computational-geometry**
**Computational geometry is a topic in computer science that focuses on solving problems in geometry. Applications of computational geometry include computer-aided design, robotics, GIS systems, and computer vision. There is no existing list for computational geometry, but it is a large enough topic in computer science to warrant a place in Awesome. I hope that it encourages other contributors to write lists for other similar topics.** …
> Add Computational Geometry

- readme.md
Adds Awesome Learn Gamedev repository
https://github.com/notpresident35/awesome-learn-gamedev
A collection of learning resources for game creators. Books, classes/courses, articles, and other lists of resources. Aimed at all disciplines that fall within the craft of game development.
Reviewed PRs: 
* [Add Developer Experience #2288 (comment)](https://github.com/sindresorhus/awesome/pull/2288#issuecomment-1214419750)
* [Add Open Source Games #2171 (comment)](https://github.com/sindresorhus/awesome/pull/2171#issuecomment-1214421247)
* [Add Processing #2373 (comment)](https://github.com/sindresorhus/awesome/pull/2373#pullrequestreview-1106175650)
- **Don't waste my time.** Do a good job, …
> Add Learn Gamedev

- readme.md
https://github.com/aleixmorgadas/awesome-engineering-strategy
Useful Engineer Strategy resources. It contains Books list, posts, and open Engineering Strategies and Open Architectures.
Reviewed PR:
- https://github.com/sindresorhus/awesome/pull/2316#issuecomment-1183511728
- https://github.com/sindresorhus/awesome/pull/2302#issuecomment-1185483548
- https://github.com/sindresorhus/awesome/pull/2370#pullrequestreview-1100158778 …
> Add Engineering Strategy

- readme.md
<https://github.com/dh-tech/awesome-digital-humanities>
Digital Humanities is a vibrant and growing academic field. It relies on digital resources and services. The best of them are compiled in this list by DHTech, an ADHO Special Interest Group.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which …
> Add Digital Humanities

- pull_request_template.md
This PR tweak the pull request template to use a check box list for contributor to check while making the PR to submit a new list.
> style: use check box list for PR template

- readme.md
**<https://github.com/mcanouil/awesome-quarto#readme>**
**This list is about [Quarto®](https://quarto.org/), an open-source scientific and technical publishing system built on Pandoc, allowing several HTML/PDF formats and computations through R/knitr or Jupyter.**
PR Reviewed:
- <https://github.com/sindresorhus/awesome/pull/2397#issuecomment-1280935757>
- <https://github.com/sindresorhus/awesome/pull/2539#issuecomment-1464991303>
Mentionned in #2242: <https://github.com/sindresorhus/awesome/issues/2242#issuecomment-1200429106>
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a …
> Add Quarto

- readme.md
https://github.com/cosmos/awesome-cosmos
This list contains all the resources necessary to start building in the Interchain/Cosmos ecosystem.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing out lint …
> Add Awesome Cosmos

- readme.md
**https://github.com/Karneades/awesome-security-card-games**
**Security card games (which are sometimes known as tabletop exercises) help train skills for various areas of security, let discuss technical topics while playing a game. It's useful to find these good security card games for training and awareness purposes.**
**The list is short but includes all the card games in the security area which I found over the last few years.**
PR's reviewed:
* https://github.com/sindresorhus/awesome/pull/2482#issuecomment-1402422558
* https://github.com/sindresorhus/awesome/pull/2478#issuecomment-1402435267
* https://github.com/sindresorhus/awesome/pull/2477#issuecomment-1402440102
* https://github.com/sindresorhus/awesome/pull/2470#issuecomment-1402461450
* …
> Add Security Card Games

- readme.md
https://github.com/rickstaa/awesome-adsb
This pull request contains an ADS-B awesome list that can be used as a reference for ADS-B enthusiasts. **Automatic Dependent Surveillance–Broadcast (ADS-B)** is a surveillance technology and form of Electronic [Conspicuity](https://en.wikipedia.org/wiki/Airborne_collision_avoidance_system#Aircraft_collision_avoidance) in which an [aircraft](https://en.wikipedia.org/wiki/Aircraft) determines its position via [satellite navigation](https://en.wikipedia.org/wiki/Satellite_navigation) or other sensors and periodically broadcasts it, enabling it to be tracked.
**Please read it multiple times. I spent a lot of time on these guidelines and most …
> Add ADS-B list

- readme.md
**[https://github.com/dstdev/awesome-hpc](https://github.com/dstdev/awesome-hpc)**
A collection of tools an resources for High Performance Computing systems.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually point out mistakes or improvement suggestions. Comments pointing …
> Add High Performance Computing

- readme.md
https://github.com/hallvaaw/awesome-biological-image-analysis
Image analysis is commonly used as a means to gain insight and deeper understanding in biological studies. It is used on all levels of the biological sciences ranging from subcellular to ecosystem levels. Although some of the principles and standards are universal, the methodology and portfolio of tools are becoming increasingly complex. This list is a collection of awesome image analysis resources for use in biological studies.
I have reviewed #2442 and #2512.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make …
> Add Biological Image Analysis

- readme.md
It was in the "Miscellaneous" section
> Move Esolangs into "Programming Languages" section

- readme.md
https://github.com/FonduAI/awesome-prompt-injection
The purpose of this repository is to provide resources for understanding, detecting, and mitigating these attacks, contributing to the creation of more secure machine learning models.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have …
> Add Prompt Injection

- readme.md
**https://github.com/sellisd/awesome-complexity**
**A list of resources on Complex systems science.**
Reviewed PRs:
https://github.com/sindresorhus/awesome/pull/2386#issuecomment-1252654547
https://github.com/sindresorhus/awesome/pull/2382#issuecomment-1248949226
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. …
> Add Complexity

- awesome.md
- code-of-conduct.md
- contributing.md
- pull_request_template.md
> Minor Grammatical and Typographical Improvements in files

- readme.md
**Link** 
https://opensource-heroes.com/awesome
**Why?** 
I think this section of Awesome pages (only of languages) with extra info adds some value for people looking for libraries. Example: awesome Python libraries for Data Visualization: https://opensource-heroes.com/awesome/python#data-visualization and now you're able to compare them by popularity, license, ...
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous …
> Add Open Source Heroes - Awesome

- readme.md
**[https://github.com/joewdavies/awesome-frontend-gis](https://github.com/joewdavies/awesome-frontend-gis)**
This list contains all the necessary resources to visualize and analyse geographic information on web browsers.
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You have to actually …
> Add Frontend GIS

- readme.md
**https://github.com/FoxFil/awesome-geocaching**
**A curated list of assets available on the Internet related to Geocaching.**
- https://github.com/sindresorhus/awesome/pull/3029#issuecomment-2083608042
- https://github.com/sindresorhus/awesome/pull/3048#issuecomment-2113368250
- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
- ❌ `- [iOS](…) - Resources and tools for iOS development.`
- ❌ `- [Framer](…)`
- ❌ `- [Framer](…) - prototyping …
> Add Geocaching

- readme.md
https://github.com/IAmCoder/awesome-lucid-dreams
A curated list of everything awesome related to lucid dreaming.
* [Add Awesome Pentest Cheat Sheets #3068](https://github.com/sindresorhus/awesome/pull/3068#pullrequestreview-2136657529)
* [Add Microsoft Azure Architecture #3029](https://github.com/sindresorhus/awesome/pull/3029#pullrequestreview-2136668070)
- ✅ `- [Framer](…) - Prototyping interactive UI designs.`
- ❌ `- [iOS](…) - Resources and tools …
> Add Lucid Dreams

- readme.md
https://github.com/Symbitic/awesome-babylonjs
This list contains resources about the popular open-source game engine Babylon.js - a framework for web and native game development written in TypeScript.
> PR's reviewed:
> 
> * #2825
> * #2843
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** You …
> Add Babylon.js

- readme.md
Remove Dead Links
The following links in the current version of the readme file doesn't work and should be removed.
**404 Error**
- [Creative Commons Media](https://github.com/shime/creative-commons-media#readme)
- [Leading and Managing](https://github.com/LappleApple/awesome-leading-and-managing#readme)
**Server Unresponsive/Down (Entry can be re-added as necessary)**
- [Open Source Heroes - Awesome](https://opensource-heroes.com/awesome)
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're …
> Remove dead links

- readme.md
https://github.com/coderabbitai/awesome-coderabbit#readme
> This list curates the best resources, tools, and documentation related to CodeRabbit, an AI-powered code review platform integrated with GitHub and GitLab. It provides context-aware feedback on pull requests, streamlining the review process for developers and teams. Adding this list enhances the Awesome project by offering a focused collection of resources that help developers improve code quality using AI-driven solutions.
My comments for the pull requests to be reviewed:
https://github.com/sindresorhus/awesome/pull/3153#issuecomment-2597562055
https://github.com/sindresorhus/awesome/pull/3232#issuecomment-2602085437
https://github.com/sindresorhus/awesome/pull/3337#issuecomment-2624209502
**Please read it multiple times. I …
> Add CodeRabbit

- readme.md
**https://github.com/DanailMinchev/awesome-payload**
**This list is about Payload, which is a Next.js native CMS (installed directly into the Next.js app) and it is a free and open source. I think it is awesome technology with great features in terms of Next.js integration and headless CMS features as well as awesome admin UI**
My PR reviews:
- https://github.com/sindresorhus/awesome/pull/3335
- https://github.com/sindresorhus/awesome/pull/3337
- https://github.com/sindresorhus/awesome/pull/3346
- https://github.com/sindresorhus/awesome/pull/3320
- https://github.com/sindresorhus/awesome/pull/3282
- https://github.com/sindresorhus/awesome/pull/2925
- https://github.com/sindresorhus/awesome/pull/2825
- https://github.com/sindresorhus/awesome/pull/3247
**Please read it multiple times. I …
> Add Payload

- readme.md
[https://github.com/NPACore/awesome-neuroimaging](https://github.com/NPACore/awesome-neuroimaging)
- hoping commits on [`awesome-lint`](https://github.com/sindresorhus/awesome-lint/commits?author=WillForan) count as one review
- on [Add Global Library](https://github.com/sindresorhus/awesome/pull/3159#issuecomment-2323019962)
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just …
> Add Neuroimaging

- readme.md
https://github.com/mikbry/awesome-webgpu
WebGPU is a Javascript API that exposes the capabilities of modern GPU hardware, allowing accelerated graphics and compute in web applications.
My comments for the pull requests to be reviewed:
[#3159 (comment)](https://github.com/sindresorhus/awesome/pull/3159#issuecomment-2316374818)  
[#3160 (comment)](https://github.com/sindresorhus/awesome/pull/3160#issuecomment-2316394590)
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good …
> Add WebGPU

- readme.md
**https://github.com/TupleType/awesome-cicd-attacks**
**Practical resources for offensive CI/CD security research. The best resources I've found in the last 3 years.**
- [✅] Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it. **Instead use [#2242](https://github.com/sindresorhus/awesome/issues/2242) for incubation visibility**.
- [✅] **Don't waste my time.** Do a good job, adhere to all the guidelines, and be responsive.
- [✅] **You have to review at least 2 other [open pull requests](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+is%3Aopen).**
- …
> Add CI/CD Attacks

- readme.md
[https://github.com/atblueprints/awesome-atproto#readme](https://github.com/atblueprints/awesome-atproto#readme)
AT Protocol (ATProto) is a federated protocol for building social applications on an open, decentralized network. Currently it's powering Bluesky and other platforms are being built for different purposes beyond microblogging.
- https://github.com/sindresorhus/awesome/pull/3320#pullrequestreview-2528686073
- https://github.com/sindresorhus/awesome/pull/3322#issuecomment-2569545978
- ✅ `- [iOS](…) - Mobile …
> Add ATProto

- readme.md
https://github.com/donBarbos/awesome-standards
This list of technical standards, they may be called requests for comments, proposals, drafts, notes, specifications, or something else
My pull request reviews:
#3316
#3312
#3308
#2804
#2780
#2763
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or simply marking the pull request as approved does not count!** …
> Add Standards

- readme.md
**https://github.com/idematos/awesome-webassembly**
**This is a curation of resources, projects, and communities related to WebAssembly (wasm) — binary instruction format for a stack-based virtual machine.**
[PRs reviewed](https://github.com/sindresorhus/awesome/pulls?q=is%3Apr+reviewed-by%3Aidematos+)
Try to prioritize unreviewed PRs, but you can also add more comments to reviewed PRs. Go through the below list when reviewing. This requirement is meant to help make the Awesome project self-sustaining. Comment here which PRs you reviewed. You're expected to put a good effort into this and to be thorough. Look at previous PR reviews for inspiration. **Just commenting “looks good” or …
> Add WebAssembly
